"use client";

import {
  AlertTriangleIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArchiveIcon,
  ArrowDown01Icon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  AudioLinesIcon,
  BarChart2Icon,
  BellIcon,
  BotIcon,
  BracesIcon,
  BrainIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  CircleHelpIcon,
  ClockIcon,
  Code2Icon,
  CopyIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  CreditCardIcon,
  DownloadIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  FileCodeIcon,
  FileIcon,
  FileJsonIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FilterIcon,
  FlagIcon,
  FlaskConicalIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  FolderIcon,
  FolderOpenIcon,
  GitBranchIcon,
  GitForkIcon,
  GitMergeIcon,
  GlobeIcon,
  HeartIcon,
  HistoryIcon,
  ImageIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  ListFilterIcon,
  ListIcon,
  ListPlusIcon,
  MenuIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MinusIcon,
  MoreHorizontalIcon,
  PaletteIcon,
  PaperclipIcon,
  PencilIcon,
  PlayIcon,
  PlusIcon,
  RefreshCwIcon,
  RotateCwIcon,
  RouteIcon,
  SearchIcon,
  SendIcon,
  Settings2Icon,
  SettingsIcon,
  Share2Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SparklesIcon,
  StarIcon,
  TableIcon,
  TargetIcon,
  TerminalIcon,
  TestTube2Icon,
  Trash2Icon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  UploadIcon,
  UserIcon,
  UserPlusIcon,
  UserRoundXIcon,
  UsersIcon,
  VolumeXIcon,
  WaypointsIcon,
  XIcon,
  ZapIcon,
} from "lucide-react";
import type * as React from "react";

import { cn } from "../../../lib/utils";

const iconMap = {
  AlertTriangleIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArchiveIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowDown01Icon,
  ArrowUpDownIcon,
  AudioLinesIcon,
  BarChart2Icon,
  BellIcon,
  BotIcon,
  BrainIcon,
  BracesIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  CircleHelpIcon,
  ClockIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  Code2Icon,
  CopyIcon,
  CreditCardIcon,
  DownloadIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  FileCodeIcon,
  FileIcon,
  FileJsonIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FilterIcon,
  FlagIcon,
  FlaskConicalIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  FolderIcon,
  FolderOpenIcon,
  GitBranchIcon,
  GitForkIcon,
  GitMergeIcon,
  GlobeIcon,
  HeartIcon,
  HistoryIcon,
  ImageIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  ListFilterIcon,
  ListIcon,
  ListPlusIcon,
  MenuIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MinusIcon,
  MoreHorizontalIcon,
  PaperclipIcon,
  PencilIcon,
  PlayIcon,
  PaletteIcon,
  PlusIcon,
  RefreshCwIcon,
  RotateCwIcon,
  RouteIcon,
  SearchIcon,
  SendIcon,
  Settings2Icon,
  SettingsIcon,
  Share2Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SparklesIcon,
  StarIcon,
  TableIcon,
  TargetIcon,
  TerminalIcon,
  TestTube2Icon,
  Trash2Icon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  UploadIcon,
  UserIcon,
  UserPlusIcon,
  UserRoundXIcon,
  UsersIcon,
  VolumeXIcon,
  WaypointsIcon,
  XIcon,
  ZapIcon,
} as const;

type IconName = keyof typeof iconMap;

type IconPlaceholderProps = React.SVGProps<SVGSVGElement> & {
  lucide?: IconName;
  tabler?: string;
  hugeicons?: string;
  phosphor?: string;
  remixicon?: string;
};

function IconPlaceholder({
  lucide = "CircleHelpIcon",
  className,
  tabler,
  hugeicons,
  phosphor,
  remixicon,
  ...props
}: IconPlaceholderProps) {
  void tabler;
  void hugeicons;
  void phosphor;
  void remixicon;

  const Icon = iconMap[lucide] ?? CircleHelpIcon;

  return (
    <Icon
      aria-hidden="true"
      className={cn("size-4 shrink-0", className)}
      {...props}
    />
  );
}

export { IconPlaceholder };
