import type { EntityMetadata } from "@repo/metadata";
import { auditCapabilities } from "./contract.ts";

export const auditEventMetadata: EntityMetadata = {
  id: "system-admin.audit",
  entity: "audit.event",
  title: "Audit trail",
  description:
    "Transaction-aware audit records with action, outcome, actor, target, route, policy, and request details.",
  labels: {
    singular: "Audit event",
    plural: "Audit events",
  },
  presentation: {
    density: "default",
    icon: "shield",
    size: "md",
    tone: "warning",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: auditCapabilities.auditRead,
    reason: "Read audit events for this tenant",
    scope: "tenant",
    subject: "audit.event",
  },
  fields: [
    {
      key: "occurredAt",
      label: "Occurred",
      kind: "date",
      required: true,
    },
    {
      key: "outcome",
      label: "Outcome",
      kind: "select",
      required: true,
    },
    {
      key: "summary",
      label: "Summary",
      kind: "text",
      required: true,
    },
    {
      key: "action",
      label: "Action",
      kind: "text",
      required: true,
    },
    {
      key: "actorRole",
      label: "Actor role",
      kind: "text",
    },
    {
      key: "actorType",
      label: "Actor type",
      kind: "text",
      required: true,
    },
    {
      key: "actorId",
      label: "Actor ID",
      kind: "text",
      required: true,
    },
    {
      key: "requestId",
      label: "Request ID",
      kind: "text",
      required: true,
    },
    {
      key: "operationId",
      label: "Operation ID",
      kind: "text",
    },
    {
      key: "diffCount",
      label: "Diffs",
      kind: "text",
    },
  ],
  table: {
    defaultSort: "occurredAt",
    title: "Event ledger",
    columns: [
      {
        key: "occurredAt",
        label: "Occurred",
        field: "occurredAt",
        kind: "date",
        sortable: true,
        width: "md",
      },
      {
        key: "outcome",
        label: "Outcome",
        field: "outcome",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
      {
        key: "summary",
        label: "Summary",
        field: "summary",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "action",
        label: "Action",
        field: "action",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "actorRole",
        label: "Actor role",
        field: "actorRole",
        kind: "text",
        sortable: true,
        width: "sm",
      },
      {
        key: "actorType",
        label: "Actor type",
        field: "actorType",
        kind: "text",
        sortable: true,
        width: "sm",
      },
      {
        key: "actorId",
        label: "Actor ID",
        field: "actorId",
        kind: "text",
        sortable: true,
        width: "md",
      },
      {
        key: "companyId",
        label: "Company ID",
        field: "companyId",
        kind: "text",
        sortable: true,
        width: "md",
      },
      {
        key: "grantId",
        label: "Grant ID",
        field: "grantId",
        kind: "text",
        width: "md",
      },
      {
        key: "module",
        label: "Module",
        field: "module",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "surface",
        label: "Surface",
        field: "surface",
        kind: "text",
        sortable: true,
        width: "sm",
      },
      {
        key: "route",
        label: "Route",
        field: "route",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "subjectType",
        label: "Subject type",
        field: "subjectType",
        kind: "text",
        width: "sm",
      },
      {
        key: "subjectId",
        label: "Subject ID",
        field: "subjectId",
        kind: "text",
        width: "md",
      },
      {
        key: "targetType",
        label: "Target type",
        field: "targetType",
        kind: "text",
        sortable: true,
        width: "sm",
      },
      {
        key: "targetId",
        label: "Target ID",
        field: "targetId",
        kind: "text",
        width: "md",
      },
      {
        key: "targetDisplayName",
        label: "Target",
        field: "targetDisplayName",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "reason",
        label: "Reason",
        field: "reason",
        kind: "text",
        width: "md",
      },
      {
        key: "policyReference",
        label: "Policy",
        field: "policyReference",
        kind: "text",
        width: "md",
      },
      {
        key: "approvalId",
        label: "Approval",
        field: "approvalId",
        kind: "text",
        width: "sm",
      },
      {
        key: "channel",
        label: "Channel",
        field: "channel",
        kind: "text",
        width: "sm",
      },
      {
        key: "requestId",
        label: "Request ID",
        field: "requestId",
        kind: "text",
        sortable: true,
        width: "md",
      },
      {
        key: "operationId",
        label: "Operation ID",
        field: "operationId",
        kind: "text",
        width: "md",
      },
      {
        key: "diffCount",
        label: "Diffs",
        field: "diffCount",
        kind: "text",
        sortable: true,
        align: "center",
        width: "sm",
      },
      {
        key: "tenantId",
        label: "Tenant",
        field: "tenantId",
        kind: "text",
        width: "sm",
      },
    ],
  },
};
