import { SURFACE_COLOR_TOKENS } from "./color-tokens";
import { ANIMATION_TOKENS } from "./motion-tokens";
import { RADIUS_TOKENS } from "./radius-tokens";
import { FONT_FEATURE_TOKENS, TEXT_UTILITY_TOKENS } from "./typography-tokens";

export type CssDeclaration = readonly [name: string, value: string];

export const TYPE2_CSS_SOURCE_GLOBS = [
  "../components/**/*.{ts,tsx}",
  "../lib/**/*.{ts,tsx}",
  "../index.ts",
] as const;

export const TYPE2_CSS_ROOT_DECLARATIONS: readonly CssDeclaration[] = [
  ["--brand-primary", "var(--tenant-primary, oklch(0.54 0.122 198))"],
  [
    "--brand-primary-foreground",
    `var(
    --tenant-primary-foreground,
    oklch(0.985 0.004 258)
  )`,
  ],
  ["--brand-secondary", "var(--tenant-secondary, oklch(0.55 0.074 154))"],
  ["--brand-accent", "var(--tenant-accent, oklch(0.71 0.112 82))"],
  ["--background", "oklch(0.982 0.004 255)"],
  ["--foreground", "oklch(0.205 0.018 264)"],
  ["--card", "oklch(0.998 0.002 255)"],
  ["--card-foreground", "oklch(0.205 0.018 264)"],
  ["--popover", "oklch(0.998 0.002 255)"],
  ["--popover-foreground", "oklch(0.205 0.018 264)"],
  ["--surface", "oklch(0.99 0.003 255)"],
  ["--surface-foreground", "oklch(0.234 0.02 264)"],
  ["--surface-muted", "oklch(0.955 0.007 255)"],
  ["--surface-accent", "oklch(0.932 0.018 198)"],
  ["--primary", "var(--brand-primary)"],
  ["--primary-foreground", "var(--brand-primary-foreground)"],
  ["--secondary", "oklch(0.948 0.011 254)"],
  ["--secondary-foreground", "oklch(0.267 0.023 264)"],
  ["--muted", "oklch(0.958 0.007 255)"],
  ["--muted-foreground", "oklch(0.48 0.024 264)"],
  ["--accent", "oklch(0.936 0.018 198)"],
  ["--accent-foreground", "oklch(0.245 0.029 218)"],
  ["--destructive", "oklch(0.577 0.22 27)"],
  ["--destructive-foreground", "oklch(0.985 0.004 258)"],
  ["--destructive-muted", "oklch(0.965 0.025 27)"],
  ["--destructive-muted-foreground", "oklch(0.42 0.12 27)"],
  ["--destructive-border", "oklch(0.82 0.08 27)"],
  ["--invert", "oklch(0.205 0.018 264)"],
  ["--invert-foreground", "oklch(0.985 0.004 258)"],
  ["--success", "oklch(0.5 0.14 154)"],
  ["--success-foreground", "oklch(0.985 0.004 258)"],
  ["--success-muted", "oklch(0.94 0.03 154)"],
  ["--success-muted-foreground", "oklch(0.28 0.06 154)"],
  ["--success-border", "oklch(0.78 0.08 154)"],
  ["--warning", "oklch(0.68 0.14 82)"],
  ["--warning-foreground", "oklch(0.18 0.02 82)"],
  ["--warning-muted", "oklch(0.95 0.04 82)"],
  ["--warning-muted-foreground", "oklch(0.34 0.06 78)"],
  ["--warning-border", "oklch(0.82 0.1 82)"],
  ["--info", "oklch(0.52 0.12 235)"],
  ["--info-foreground", "oklch(0.985 0.004 258)"],
  ["--info-muted", "oklch(0.94 0.03 235)"],
  ["--info-muted-foreground", "oklch(0.3 0.05 250)"],
  ["--info-border", "oklch(0.78 0.08 235)"],
  ["--border", "oklch(0.887 0.013 255)"],
  ["--input", "oklch(0.887 0.013 255)"],
  ["--ring", "var(--brand-primary)"],
  ["--chart-1", "var(--brand-primary)"],
  ["--chart-2", "var(--brand-secondary)"],
  ["--chart-3", "var(--brand-accent)"],
  ["--chart-4", "oklch(0.58 0.14 25)"],
  ["--chart-5", "oklch(0.53 0.101 285)"],
  ["--radius", "0.625rem"],
  ["--radius-control", "0.5rem"],
  ["--radius-panel", "0.75rem"],
  ["--radius-2xl", "1rem"],
  ["--radius-3xl", "1.25rem"],
  ["--radius-4xl", "1.5rem"],
  ["--density-control-height", "2.25rem"],
  ["--density-table-row-height", "2.75rem"],
  ["--elevation-xs", "0 1px 1px oklch(0.1 0.01 260 / 0.05)"],
  ["--elevation-sm", "0 1px 2px oklch(0.1 0.01 260 / 0.07)"],
  ["--elevation-md", "0 10px 28px oklch(0.1 0.01 260 / 0.08)"],
  ["--sidebar", "var(--surface)"],
  ["--sidebar-foreground", "var(--surface-foreground)"],
  ["--sidebar-primary", "var(--primary)"],
  ["--sidebar-primary-foreground", "var(--primary-foreground)"],
  ["--sidebar-accent", "var(--surface-accent)"],
  ["--sidebar-accent-foreground", "var(--accent-foreground)"],
  ["--sidebar-border", "var(--border)"],
  ["--sidebar-ring", "var(--ring)"],
] as const;

export const TYPE2_CSS_DARK_DECLARATIONS: readonly CssDeclaration[] = [
  ["--brand-primary", "var(--tenant-primary, oklch(0.72 0.112 198))"],
  [
    "--brand-primary-foreground",
    `var(
    --tenant-primary-foreground,
    oklch(0.174 0.014 264)
  )`,
  ],
  ["--brand-secondary", "var(--tenant-secondary, oklch(0.76 0.105 154))"],
  ["--brand-accent", "var(--tenant-accent, oklch(0.82 0.116 82))"],
  ["--background", "oklch(0.17 0.014 264)"],
  ["--foreground", "oklch(0.958 0.005 258)"],
  ["--card", "oklch(0.205 0.016 264)"],
  ["--card-foreground", "oklch(0.958 0.005 258)"],
  ["--popover", "oklch(0.205 0.016 264)"],
  ["--popover-foreground", "oklch(0.958 0.005 258)"],
  ["--surface", "oklch(0.218 0.016 264)"],
  ["--surface-foreground", "oklch(0.948 0.006 258)"],
  ["--surface-muted", "oklch(0.274 0.016 264)"],
  ["--surface-accent", "oklch(0.305 0.027 198)"],
  ["--primary", "var(--brand-primary)"],
  ["--primary-foreground", "var(--brand-primary-foreground)"],
  ["--secondary", "oklch(0.288 0.018 264)"],
  ["--secondary-foreground", "oklch(0.958 0.005 258)"],
  ["--muted", "oklch(0.268 0.016 264)"],
  ["--muted-foreground", "oklch(0.738 0.014 260)"],
  ["--accent", "oklch(0.31 0.027 198)"],
  ["--accent-foreground", "oklch(0.958 0.005 258)"],
  ["--destructive", "oklch(0.68 0.196 25)"],
  ["--destructive-foreground", "oklch(0.174 0.014 264)"],
  ["--destructive-muted", "oklch(0.28 0.055 27)"],
  ["--destructive-muted-foreground", "oklch(0.9 0.055 27)"],
  ["--destructive-border", "oklch(0.48 0.09 27)"],
  ["--invert", "oklch(0.268 0.016 264)"],
  ["--invert-foreground", "oklch(0.985 0.004 258)"],
  ["--success", "oklch(0.72 0.13 154)"],
  ["--success-foreground", "oklch(0.17 0.014 264)"],
  ["--success-muted", "oklch(0.25 0.04 154)"],
  ["--success-muted-foreground", "oklch(0.86 0.08 154)"],
  ["--success-border", "oklch(0.45 0.08 154)"],
  ["--warning", "oklch(0.78 0.12 84)"],
  ["--warning-foreground", "oklch(0.18 0.014 84)"],
  ["--warning-muted", "oklch(0.27 0.04 84)"],
  ["--warning-muted-foreground", "oklch(0.9 0.08 84)"],
  ["--warning-border", "oklch(0.48 0.08 84)"],
  ["--info", "oklch(0.72 0.1 235)"],
  ["--info-foreground", "oklch(0.17 0.014 264)"],
  ["--info-muted", "oklch(0.25 0.04 235)"],
  ["--info-muted-foreground", "oklch(0.88 0.06 235)"],
  ["--info-border", "oklch(0.46 0.07 235)"],
  ["--border", "oklch(0.322 0.019 264)"],
  ["--input", "oklch(0.322 0.019 264)"],
  ["--ring", "var(--brand-primary)"],
  ["--chart-1", "var(--brand-primary)"],
  ["--chart-2", "var(--brand-secondary)"],
  ["--chart-3", "var(--brand-accent)"],
  ["--chart-4", "oklch(0.72 0.151 25)"],
  ["--chart-5", "oklch(0.75 0.109 285)"],
  ["--elevation-xs", "0 1px 1px oklch(0 0 0 / 0.2)"],
  ["--elevation-sm", "0 1px 2px oklch(0 0 0 / 0.24)"],
  ["--elevation-md", "0 18px 48px oklch(0 0 0 / 0.26)"],
  ["--sidebar", "var(--surface)"],
  ["--sidebar-foreground", "var(--surface-foreground)"],
  ["--sidebar-primary", "var(--primary)"],
  ["--sidebar-primary-foreground", "var(--primary-foreground)"],
  ["--sidebar-accent", "var(--surface-accent)"],
  ["--sidebar-accent-foreground", "var(--accent-foreground)"],
  ["--sidebar-border", "var(--border)"],
  ["--sidebar-ring", "var(--ring)"],
] as const;

export const TYPE2_CSS_COMPACT_DENSITY_DECLARATIONS: readonly CssDeclaration[] =
  [
    ["--density-control-height", "2rem"],
    ["--density-table-row-height", "2.375rem"],
    ["--radius-control", "0.375rem"],
  ] as const;

export const TYPE2_CSS_COMFORTABLE_DENSITY_DECLARATIONS: readonly CssDeclaration[] =
  [
    ["--density-control-height", "2.75rem"],
    ["--density-table-row-height", "3.25rem"],
  ] as const;

export const TYPE2_CSS_THEME_DECLARATIONS: readonly CssDeclaration[] = [
  ["--color-background", "var(--background)"],
  ["--color-foreground", "var(--foreground)"],
  ["--font-sans", "ui-sans-serif, system-ui, sans-serif"],
  [
    "--font-mono",
    `ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono",
    "Courier New", monospace`,
  ],
  ["--color-ring", "var(--ring)"],
  ["--color-input", "var(--input)"],
  ["--color-border", "var(--border)"],
  ["--color-surface", "var(--surface)"],
  ["--color-surface-foreground", "var(--surface-foreground)"],
  ["--color-surface-muted", "var(--surface-muted)"],
  ["--color-surface-accent", "var(--surface-accent)"],
  ["--color-destructive", "var(--destructive)"],
  ["--color-destructive-foreground", "var(--destructive-foreground)"],
  ["--color-destructive-muted", "var(--destructive-muted)"],
  [
    "--color-destructive-muted-foreground",
    "var(--destructive-muted-foreground)",
  ],
  ["--color-destructive-border", "var(--destructive-border)"],
  ["--color-invert", "var(--invert)"],
  ["--color-invert-foreground", "var(--invert-foreground)"],
  ["--color-success", "var(--success)"],
  ["--color-success-foreground", "var(--success-foreground)"],
  ["--color-success-muted", "var(--success-muted)"],
  ["--color-success-muted-foreground", "var(--success-muted-foreground)"],
  ["--color-success-border", "var(--success-border)"],
  ["--color-warning", "var(--warning)"],
  ["--color-warning-foreground", "var(--warning-foreground)"],
  ["--color-warning-muted", "var(--warning-muted)"],
  ["--color-warning-muted-foreground", "var(--warning-muted-foreground)"],
  ["--color-warning-border", "var(--warning-border)"],
  ["--color-info", "var(--info)"],
  ["--color-info-foreground", "var(--info-foreground)"],
  ["--color-info-muted", "var(--info-muted)"],
  ["--color-info-muted-foreground", "var(--info-muted-foreground)"],
  ["--color-info-border", "var(--info-border)"],
  ["--color-accent-foreground", "var(--accent-foreground)"],
  ["--color-accent", "var(--accent)"],
  ["--color-muted-foreground", "var(--muted-foreground)"],
  ["--color-muted", "var(--muted)"],
  ["--color-secondary-foreground", "var(--secondary-foreground)"],
  ["--color-secondary", "var(--secondary)"],
  ["--color-primary-foreground", "var(--primary-foreground)"],
  ["--color-primary", "var(--primary)"],
  ["--color-popover-foreground", "var(--popover-foreground)"],
  ["--color-popover", "var(--popover)"],
  ["--color-card-foreground", "var(--card-foreground)"],
  ["--color-card", "var(--card)"],
  ["--color-chart-1", "var(--chart-1)"],
  ["--color-chart-2", "var(--chart-2)"],
  ["--color-chart-3", "var(--chart-3)"],
  ["--color-chart-4", "var(--chart-4)"],
  ["--color-chart-5", "var(--chart-5)"],
  ["--color-sidebar", "var(--sidebar)"],
  ["--color-sidebar-foreground", "var(--sidebar-foreground)"],
  ["--color-sidebar-primary", "var(--sidebar-primary)"],
  ["--color-sidebar-primary-foreground", "var(--sidebar-primary-foreground)"],
  ["--color-sidebar-accent", "var(--sidebar-accent)"],
  ["--color-sidebar-accent-foreground", "var(--sidebar-accent-foreground)"],
  ["--color-sidebar-border", "var(--sidebar-border)"],
  ["--color-sidebar-ring", "var(--sidebar-ring)"],
  ["--radius-sm", "calc(var(--radius) - 0.25rem)"],
  ["--radius-md", "calc(var(--radius) - 0.125rem)"],
  ["--radius-lg", "var(--radius)"],
  ["--radius-xl", "calc(var(--radius) + 0.25rem)"],
  ["--radius-2xl", "var(--radius-2xl)"],
  ["--radius-3xl", "var(--radius-3xl)"],
  ["--radius-4xl", "var(--radius-4xl)"],
  ["--radius-control", "var(--radius-control)"],
  ["--radius-panel", "var(--radius-panel)"],
  ["--animate-shimmer", "shimmer 1.8s linear infinite"],
  ["--shadow-xs", "var(--elevation-xs)"],
  ["--shadow-sm", "var(--elevation-sm)"],
  ["--shadow-md", "var(--elevation-md)"],
] as const;

export const TYPE2_CSS_KEYFRAMES = {
  shimmer: [
    "0% {",
    "  background-position: -200% 0;",
    "}",
    "",
    "100% {",
    "  background-position: 200% 0;",
    "}",
  ] as const,
} as const;

export const TYPE2_CSS_UTILITIES = [
  ["text-tabular", "font-variant-numeric: tabular-nums;"],
  ["font-rlig", 'font-feature-settings: "rlig";'],
  ["font-calt", 'font-feature-settings: "calt";'],
  ["control-density", "min-height: var(--density-control-height);"],
  ["row-density", "min-height: var(--density-table-row-height);"],
] as const;

export function validateType2CssTokens(): void {
  if (
    SURFACE_COLOR_TOKENS.length !== 4 ||
    !SURFACE_COLOR_TOKENS.includes("surface") ||
    !RADIUS_TOKENS.includes("2xl") ||
    !RADIUS_TOKENS.includes("3xl") ||
    !RADIUS_TOKENS.includes("4xl") ||
    ANIMATION_TOKENS[0] !== "shimmer" ||
    !FONT_FEATURE_TOKENS.includes("rlig") ||
    !FONT_FEATURE_TOKENS.includes("calt") ||
    !TEXT_UTILITY_TOKENS.includes("text-tabular")
  ) {
    throw new Error("type2 CSS tokens do not match the design-system contract");
  }
}
