import type { CssDeclaration } from "../tokens/css-theme";
import {
  GLOBALS_CSS_COMFORTABLE_DENSITY_DECLARATIONS,
  GLOBALS_CSS_COMPACT_DENSITY_DECLARATIONS,
  GLOBALS_CSS_DARK_DECLARATIONS,
  GLOBALS_CSS_KEYFRAMES,
  GLOBALS_CSS_ROOT_DECLARATIONS,
  GLOBALS_CSS_SOURCE_GLOBS,
  GLOBALS_CSS_THEME_DECLARATIONS,
  GLOBALS_CSS_UTILITIES,
  validateGlobalsCssTokens,
} from "../tokens/css-theme";

const GENERATED_BANNER = `/**
 * Generated by @repo/design-system — do not edit manually.
 * Run: pnpm --filter @repo/design-system globals:css
 */
`;

function renderDeclarations(declarations: readonly CssDeclaration[]): string {
  return declarations.map(([name, value]) => `  ${name}: ${value};`).join("\n");
}

function renderBlock(
  selector: string,
  declarations: readonly CssDeclaration[]
): string {
  return `${selector} {\n${renderDeclarations(declarations)}\n}`;
}

function renderUtility(name: string, body: string): string {
  return `@utility ${name} {\n${body}\n}`;
}

function renderKeyframes(name: keyof typeof GLOBALS_CSS_KEYFRAMES): string {
  const lines = GLOBALS_CSS_KEYFRAMES[name];
  return `@keyframes ${name} {\n${lines
    .map((line) => (line ? `    ${line}` : ""))
    .join("\n")}\n  }`;
}

function assertAdapterCoverage(): void {
  validateGlobalsCssTokens();
}

export function renderGlobalsCss(): string {
  assertAdapterCoverage();

  return [
    GENERATED_BANNER.trimEnd(),
    '@import "tailwindcss";',
    '@import "tw-animate-css";',
    '@import "shadcn/tailwind.css";',
    "",
    ...GLOBALS_CSS_SOURCE_GLOBS.map((source) => `@source "${source}";`),
    "",
    "@custom-variant dark (&:where(.dark, .dark *));",
    "",
    renderBlock(":root", GLOBALS_CSS_ROOT_DECLARATIONS),
    "",
    renderBlock(".dark", GLOBALS_CSS_DARK_DECLARATIONS),
    "",
    renderBlock(
      '[data-density="compact"]',
      GLOBALS_CSS_COMPACT_DENSITY_DECLARATIONS
    ),
    "",
    renderBlock(
      '[data-density="comfortable"]',
      GLOBALS_CSS_COMFORTABLE_DENSITY_DECLARATIONS
    ),
    "",
    `@theme inline {\n${renderDeclarations(GLOBALS_CSS_THEME_DECLARATIONS)}\n\n  ${renderKeyframes(
      "shimmer"
    )}\n}`,
    "",
    "@layer base {\n  * {\n    @apply border-border outline-ring/50;\n  }\n\n  html {\n    @apply bg-background text-foreground;\n  }\n\n  body {\n    @apply min-h-dvh bg-background text-foreground antialiased;\n  }\n\n  button,\n  input,\n  select,\n  textarea {\n    @apply [font:inherit];\n  }\n}",
    "",
    ...GLOBALS_CSS_UTILITIES.flatMap(([name, body]) => [
      renderUtility(name, `  ${body}`),
      "",
    ]),
    "",
    "@media (prefers-reduced-motion: reduce) {\n  *,\n  ::before,\n  ::after {\n    animation-duration: 0.01ms !important;\n    animation-iteration-count: 1 !important;\n    scroll-behavior: auto !important;\n    transition-duration: 0.01ms !important;\n  }\n}",
  ].join("\n");
}

type ParsedCssSnapshot = {
  sources: string[];
  utilities: string[];
  keyframes: string[];
  variables: {
    root: Record<string, string>;
    dark: Record<string, string>;
    density: {
      compact: Record<string, string>;
      comfortable: Record<string, string>;
    };
    theme: Record<string, string>;
  };
};

function normalizeValue(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function extractBalancedBlock(css: string, marker: string): string {
  const start = css.indexOf(`${marker} {`);

  if (start === -1) {
    throw new Error(`Could not find block marker: ${marker}`);
  }

  const openBrace = start + marker.length + 1;
  let depth = 0;

  for (let index = openBrace; index < css.length; index += 1) {
    const char = css[index];

    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;

      if (depth === 0) {
        return css.slice(openBrace + 1, index);
      }
    }
  }

  throw new Error(`Could not find closing brace for block marker: ${marker}`);
}

function extractCustomProperties(block: string): Record<string, string> {
  const entries: [string, string][] = [];
  const declarationRegex = /(--[a-z0-9-]+):\s*([^;]+);/g;

  for (const match of block.matchAll(declarationRegex)) {
    const name = match[1];

    if (!name) {
      continue;
    }

    entries.push([name, normalizeValue(match[2] ?? "")]);
  }

  return Object.fromEntries(entries);
}

function requireCapture(match: RegExpMatchArray): string {
  const value = match[1];

  if (!value) {
    throw new Error(`Could not read regex capture from ${match[0]}`);
  }

  return value;
}

function parseCss(css: string): ParsedCssSnapshot {
  const themeBlock = extractBalancedBlock(css, "@theme inline");

  return {
    sources: [...css.matchAll(/^@source\s+"([^"]+)";$/gm)].map(requireCapture),
    utilities: [...css.matchAll(/^@utility\s+([a-z0-9-]+)\s*\{/gm)].map(
      requireCapture
    ),
    keyframes: [...themeBlock.matchAll(/@keyframes\s+([a-z0-9-]+)\s*\{/g)].map(
      requireCapture
    ),
    variables: {
      root: extractCustomProperties(extractBalancedBlock(css, ":root")),
      dark: extractCustomProperties(extractBalancedBlock(css, ".dark")),
      density: {
        compact: extractCustomProperties(
          extractBalancedBlock(css, '[data-density="compact"]')
        ),
        comfortable: extractCustomProperties(
          extractBalancedBlock(css, '[data-density="comfortable"]')
        ),
      },
      theme: extractCustomProperties(themeBlock),
    },
  };
}

export function compareGlobalsCss(actualCss: string): {
  equal: boolean;
  expected: string;
  actual: string;
} {
  const expected = renderGlobalsCss();
  const expectedSnapshot = parseCss(expected);
  const actualSnapshot = parseCss(actualCss);

  return {
    equal: JSON.stringify(expectedSnapshot) === JSON.stringify(actualSnapshot),
    expected,
    actual: actualCss,
  };
}
