packages:
  - "apps/*"
  - "packages/*"
  - "packages/features/*"
  - "packages/features/*/*"
  - "packages/features/*/*/*"
  - "packages/integrations/*"
  - "packages/jurisdictions/*"
  - "turbo/generators"

catalog:
  "@payloadcms/richtext-lexical": ^3.85.0
  "@liveblocks/client": ^3.15.0
  "@liveblocks/node": ^3.15.0
  "@liveblocks/react": ^3.15.0
  "@ai-sdk/openai": ^3.0.41
  "@ai-sdk/react": ^3.0.199
  "@biomejs/biome": ^2.4.6
  knip: ^6.16.1
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-slot": ^1.2.5
  "@tailwindcss/postcss": ^4.2.1
  postcss-load-config: ^6.0.1
  "@logtail/next": ^0.3.1
  "@next/bundle-analyzer": ^16.1.6
  "@next/third-parties": 16.1.6
  "@aws-sdk/client-s3": 3.1063.0
  "@react-email/components": 1.0.8
  "@react-email/preview-server": 5.2.9
  "prom-client": ^15.1.3
  "@supabase/ssr": 0.10.3
  "@supabase/supabase-js": 2.107.0
  "@sentry/browser": ^10.56.0
  "@sentry/nextjs": ^10.42.0
  "@t3-oss/env-nextjs": ^0.13.10
  "@turbo/gen": ^2.8.14
  "@storybook/react": ^10.4.2
  "@storybook/react-vite": ^10.4.2
  "@types/lodash.merge": ^4.6.9
  "@types/node": ^25.3.5
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^1.6.1
  "@vercel/toolbar": ^0.2.6
  "@vercel/blob": ^2.3.1
  "class-variance-authority": ^0.7.1
  "clsx": ^2.1.1
  ai: ^6.0.116
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  lodash.merge: ^4.6.2
  lucide-react: ^0.577.0
  meilisearch: ^0.54.0
  next: ^16.1.6
  next-themes: ^0.4.6
  nats: ^2.29.3
  postgres: ^3.4.9
  posthog-js: ^1.359.1
  posthog-node: ^5.28.0
  postcss: ^8.5.8
  payload: ^3.85.0
  pino: ^10.3.1
  pino-pretty: ^13.1.3
  react: ^19.2.4
  react-dom: ^19.2.4
  redis: ^5.9.0
  flags: ^4.1.0
  svix: ^1.95.1
  sonner: ^2.0.7
  resend: ^6.9.3
  react-email: 5.2.9
  schema-dts: ^1.1.5
  server-only: ^0.0.1
  tsup: ^8.5.1
  streamdown: ^2.4.0
  tsx: ^4.20.3
  stripe: ^20.4.1
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.1
  tw-animate-css: ^1.4.0
  shadcn: ^4.10.0
  storybook: ^10.2.16
  turbo: ^2.8.14
  typescript: ^5.9.3
  ultracite: 7.8.1
  zod: 4.3.6

catalogMode: strict

