import type { EntityMetadata } from "@repo/metadata";

export const companyMetadata: EntityMetadata = {
  id: "master-data.companies",
  customization: {
    presentation: {
      density: true,
      icon: true,
      size: true,
      tone: true,
      variant: true,
    },
    scopes: ["tenant", "company"],
  },
  entity: "company",
  title: "Companies",
  description:
    "Tenant-scoped legal entity master-data used to govern organization hierarchy, company grants, and operational scope.",
  labels: {
    singular: "Company",
    plural: "Companies",
  },
  presentation: {
    density: "default",
    icon: "building-2",
    size: "md",
    tone: "info",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: "master-data.companies:read",
    reason: "Read company records",
    scope: "tenant",
    subject: "company",
  },
  fields: [
    {
      customization: { label: true, order: true, placeholder: true },
      key: "code",
      label: "Code",
      kind: "text",
      required: true,
      placeholder: "COMP-001",
      validationHint: "Use a stable company code inside the tenant.",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "name",
      label: "Name",
      kind: "text",
      required: true,
      placeholder: "Acme Holdings",
      validationHint: "Use the legal or display name.",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "parentCompanyId",
      label: "Parent company",
      kind: "text",
      placeholder: "Parent company ID",
      validationHint: "Parent company must belong to the same tenant.",
    },
    {
      customization: { label: true, order: true },
      key: "isGroup",
      label: "Group company",
      kind: "switch",
      validationHint:
        "Use group companies to organize hierarchy; access still requires explicit grants.",
    },
    {
      customization: { label: true, order: true },
      key: "status",
      label: "Status",
      kind: "select",
      required: true,
      validationHint:
        "Use active for operating entities and inactive for archived entities.",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "countryCode",
      label: "Country",
      kind: "select",
      placeholder: "US",
      validationHint: "Use a two-letter ISO country code.",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "currencyCode",
      label: "Currency",
      kind: "select",
      placeholder: "USD",
      validationHint: "Use a three-letter ISO currency code.",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "taxId",
      label: "Tax ID",
      kind: "text",
      placeholder: "Tax registration",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "registrationNumber",
      label: "Registration number",
      kind: "text",
      placeholder: "Company registry number",
    },
    {
      customization: { label: true, order: true },
      key: "establishedOn",
      label: "Established on",
      kind: "date",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "email",
      label: "Primary email",
      kind: "text",
      placeholder: "finance@example.com",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "phone",
      label: "Phone",
      kind: "text",
      placeholder: "+1 555 0100",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "website",
      label: "Website",
      kind: "text",
      placeholder: "https://example.com",
    },
    {
      customization: { label: true, order: true, placeholder: true },
      key: "description",
      label: "Description",
      kind: "textarea",
      placeholder: "Legal entity notes",
    },
  ],
  filters: [
    {
      customization: { hidden: true, label: true },
      key: "company-code",
      label: "Code",
      field: "code",
      kind: "text",
      operator: "contains",
      placeholder: "Search code",
    },
    {
      customization: { hidden: true, label: true },
      key: "company-status",
      label: "Status",
      field: "status",
      kind: "status",
      operator: "equals",
      options: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
      ],
    },
    {
      customization: { hidden: true, label: true },
      key: "company-parent",
      label: "Parent company",
      field: "parentCompanyId",
      kind: "text",
      operator: "equals",
      placeholder: "Parent company ID",
    },
  ],
  forms: [
    {
      customization: { label: true, layout: true, sectionKeys: true },
      key: "company-create",
      label: "Create company",
      fieldKeys: [
        "code",
        "name",
        "parentCompanyId",
        "isGroup",
        "status",
        "countryCode",
        "currencyCode",
        "taxId",
        "registrationNumber",
        "establishedOn",
        "email",
        "phone",
        "website",
        "description",
      ],
      sectionKeys: [
        "company-identity",
        "company-hierarchy",
        "company-legal",
        "company-contact",
        "company-lifecycle",
      ],
      submitActionKey: "company-create",
      cancelActionKey: "cancel",
      layout: "grid",
    },
    {
      customization: { label: true, layout: true, sectionKeys: true },
      key: "company-edit",
      label: "Edit company",
      fieldKeys: [
        "code",
        "name",
        "parentCompanyId",
        "isGroup",
        "status",
        "countryCode",
        "currencyCode",
        "taxId",
        "registrationNumber",
        "establishedOn",
        "email",
        "phone",
        "website",
        "description",
      ],
      sectionKeys: [
        "company-identity",
        "company-hierarchy",
        "company-legal",
        "company-contact",
        "company-lifecycle",
      ],
      submitActionKey: "company-save",
      cancelActionKey: "cancel",
      layout: "grid",
    },
  ],
  actions: [
    {
      customization: { hidden: true, label: true, placement: true, safe: true },
      key: "company-create",
      label: "Create",
      kind: "create",
      placement: "primary",
      permissionHint: "master-data.companies:write",
    },
    {
      customization: { hidden: true, label: true, placement: true, safe: true },
      key: "company-save",
      label: "Save changes",
      kind: "update",
      placement: "primary",
      permissionHint: "master-data.companies:write",
    },
    {
      customization: { safe: false },
      key: "company-archive",
      label: "Archive",
      kind: "archive",
      placement: "overflow",
      dangerous: true,
      confirmMessage: "Archive this company record?",
      permissionHint: "master-data.companies:write",
      stateTransition: { from: ["active"], to: "inactive" },
    },
    {
      customization: { safe: false },
      key: "company-restore",
      label: "Restore",
      kind: "restore",
      placement: "overflow",
      permissionHint: "master-data.companies:write",
      stateTransition: { from: ["inactive"], to: "active" },
    },
  ],
  sections: [
    {
      customization: { columns: true, fieldKeys: true, label: true },
      key: "company-identity",
      label: "Identity",
      fieldKeys: ["code", "name"],
      columns: 2,
    },
    {
      customization: { columns: true, fieldKeys: true, label: true },
      key: "company-hierarchy",
      label: "Hierarchy",
      fieldKeys: ["parentCompanyId", "isGroup"],
      columns: 2,
    },
    {
      customization: { columns: true, fieldKeys: true, label: true },
      key: "company-legal",
      label: "Legal",
      fieldKeys: [
        "countryCode",
        "currencyCode",
        "taxId",
        "registrationNumber",
        "establishedOn",
      ],
      columns: 2,
      collapsible: true,
    },
    {
      customization: {
        columns: true,
        fieldKeys: true,
        hidden: true,
        label: true,
      },
      key: "company-contact",
      label: "Contact",
      fieldKeys: ["email", "phone", "website", "description"],
      columns: 2,
      collapsible: true,
    },
    {
      customization: { columns: true, fieldKeys: true, label: true },
      key: "company-lifecycle",
      label: "Lifecycle",
      fieldKeys: ["status"],
      columns: 1,
      collapsible: true,
    },
  ],
  states: [
    { key: "company-draft", label: "Draft", uiState: "empty", tone: "neutral" },
    { key: "company-ready", label: "Ready", uiState: "ready", tone: "success" },
    {
      key: "company-inactive",
      label: "Inactive",
      uiState: "forbidden",
      tone: "warning",
    },
  ],
  table: {
    customization: { columns: true, defaultSort: true, title: true },
    defaultSort: "name",
    title: "Company directory",
    columns: [
      {
        customization: { hidden: true, label: true, order: true, width: true },
        key: "code",
        label: "Code",
        field: "code",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        customization: { hidden: true, label: true, order: true, width: true },
        key: "name",
        label: "Name",
        field: "name",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        customization: { hidden: true, label: true, order: true, width: true },
        key: "parentCompanyId",
        label: "Parent",
        field: "parentCompanyId",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        customization: { align: true, hidden: true, label: true, order: true },
        key: "isGroup",
        label: "Group",
        field: "isGroup",
        sortable: true,
        filterable: true,
        align: "center",
      },
      {
        customization: { align: true, hidden: true, label: true, order: true },
        key: "status",
        label: "Status",
        field: "status",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
      {
        customization: { hidden: true, label: true, order: true, width: true },
        key: "countryCode",
        label: "Country",
        field: "countryCode",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        customization: { hidden: true, label: true, order: true, width: true },
        key: "currencyCode",
        label: "Currency",
        field: "currencyCode",
        sortable: true,
        filterable: true,
        width: "sm",
      },
    ],
  },
};
