import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type {
  MetadataUiManifest,
  MetadataUiManifestEntry,
} from "../metadata-ui.manifest.ts";
import { metadataUiManifest } from "../metadata-ui.manifest.ts";
import {
  resolveFromModule,
  resolveModuleFilename,
} from "./module-location.mts";

export const packageRoot = resolveFromModule(import.meta.url, "..");
export const generatedRoot = resolve(packageRoot, "src", "generated");
export const readmePath = resolve(packageRoot, "README.md");
export const generatedReadmeSectionMarkers = {
  end: "<!-- metadata-ui-generated-renderer-catalog:end -->",
  start: "<!-- metadata-ui-generated-renderer-catalog:start -->",
} as const;

const manifestKindOrder = {
  action: 0,
  field: 1,
  section: 2,
} as const satisfies Record<MetadataUiManifestEntry["kind"], number>;

export type MetadataUiManifestEntriesByKind = {
  action: readonly MetadataUiManifestEntry[];
  field: readonly MetadataUiManifestEntry[];
  section: readonly MetadataUiManifestEntry[];
};

export function invariant(
  condition: unknown,
  message: string
): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

export function isEntrypoint(moduleUrl: string): boolean {
  const entry = process.argv[1];

  return entry ? resolve(entry) === resolveModuleFilename(moduleUrl) : false;
}

export function getManifest(): MetadataUiManifest {
  return metadataUiManifest;
}

export function compareManifestEntries(
  left: MetadataUiManifestEntry,
  right: MetadataUiManifestEntry
): number {
  return (
    manifestKindOrder[left.kind] - manifestKindOrder[right.kind] ||
    left.registryKey.localeCompare(right.registryKey) ||
    left.rendererExport.localeCompare(right.rendererExport)
  );
}

export function getManifestEntries(): readonly MetadataUiManifestEntry[] {
  return [...metadataUiManifest.renderers].sort(compareManifestEntries);
}

export function groupManifestEntries(
  entries: readonly MetadataUiManifestEntry[] = getManifestEntries()
): MetadataUiManifestEntriesByKind {
  return {
    action: entries.filter((entry) => entry.kind === "action"),
    field: entries.filter((entry) => entry.kind === "field"),
    section: entries.filter((entry) => entry.kind === "section"),
  };
}

export function normalizeFileContent(source: string): string {
  return source.replace(/\r\n/g, "\n");
}

export function renderGeneratedHeader(scriptName: string): string {
  return [
    `// This file is auto-generated by ${scriptName}.`,
    "// Do not edit manually.",
    "",
  ].join("\n");
}

export function quote(value: string): string {
  return JSON.stringify(value);
}

export function resolveRendererSourcePath(
  entry: MetadataUiManifestEntry
): string {
  const sourceBasePath = resolve(
    packageRoot,
    "src",
    "generated",
    entry.rendererPath
  );
  const candidates = [
    sourceBasePath,
    `${sourceBasePath}.ts`,
    `${sourceBasePath}.tsx`,
    resolve(sourceBasePath, "index.ts"),
    resolve(sourceBasePath, "index.tsx"),
  ];

  const match = candidates.find((candidate) => existsSync(candidate));

  if (!match) {
    throw new Error(
      `Manifest entry '${entry.kind}:${entry.registryKey}' points to a missing renderer path '${entry.rendererPath}'.`
    );
  }

  return match;
}

export function sourceHasNamedExport(
  sourcePath: string,
  exportName: string
): boolean {
  const source = readFileSync(sourcePath, "utf8");
  const patterns = [
    new RegExp(`export\\s+(?:async\\s+)?function\\s+${exportName}\\b`),
    new RegExp(`export\\s+(?:const|class|let|var)\\s+${exportName}\\b`),
    new RegExp(`export\\s*\\{[^}]*\\b${exportName}\\b[^}]*\\}`),
  ];

  return patterns.some((pattern) => pattern.test(source));
}

export function writeGeneratedOutput(
  relativePath: string,
  content: string,
  check = false
): boolean {
  const absolutePath = resolve(packageRoot, relativePath);
  const normalizedContent = `${normalizeFileContent(content).trimEnd()}\n`;
  const currentContent = existsSync(absolutePath)
    ? normalizeFileContent(readFileSync(absolutePath, "utf8"))
    : null;

  if (currentContent === normalizedContent) {
    return false;
  }

  if (check) {
    throw new Error(`${relativePath} is out of date. Run 'pnpm generate'.`);
  }

  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, normalizedContent, "utf8");
  return true;
}

export function updateReadmeSection(
  sectionContent: string,
  check = false
): boolean {
  const readme = normalizeFileContent(readFileSync(readmePath, "utf8"));
  const { start, end } = generatedReadmeSectionMarkers;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  const replacement = `${start}\n${sectionContent.trimEnd()}\n${end}`;

  invariant(
    pattern.test(readme),
    "README.md is missing metadata-ui generated renderer catalog markers."
  );

  const nextReadme = readme.replace(pattern, replacement);

  if (nextReadme === readme) {
    return false;
  }

  if (check) {
    throw new Error(
      "README.md renderer catalog is out of date. Run 'pnpm generate'."
    );
  }

  writeFileSync(readmePath, nextReadme, "utf8");
  return true;
}
