import type { EntityMetadata } from "@repo/metadata";

export const jobPositionMetadata: EntityMetadata = {
  id: "master-data.job-positions",
  entity: "job-position",
  title: "Job Positions",
  description:
    "Governed metadata for job positions shared across organization design, employee assignments, and workforce planning.",
  labels: {
    singular: "Job position",
    plural: "Job positions",
  },
  presentation: {
    density: "default",
    icon: "briefcase-business",
    size: "md",
    tone: "info",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: "master-data.job-positions:read",
    reason: "Read job position records",
    scope: "tenant",
    subject: "job-position",
  },
  fields: [
    {
      key: "code",
      label: "Code",
      kind: "text",
      required: true,
      placeholder: "POS-001",
      validationHint: "Use a stable job position code.",
    },
    {
      key: "title",
      label: "Title",
      kind: "text",
      required: true,
      placeholder: "Senior Accountant",
      validationHint: "Use the governed position title.",
    },
    {
      key: "orgUnitId",
      label: "Org unit",
      kind: "text",
      required: true,
      placeholder: "Org unit ID",
      validationHint: "Reference the owning organizational unit.",
    },
    {
      key: "status",
      label: "Status",
      kind: "select",
      required: true,
      validationHint:
        "Use planned before activation, frozen for temporary stops, and closed for retired positions.",
    },
    {
      key: "costCenterCode",
      label: "Cost center",
      kind: "text",
      required: false,
      placeholder: "CC-100",
      validationHint: "Reference the governed cost center code when assigned.",
    },
    {
      key: "locationCode",
      label: "Location",
      kind: "text",
      required: false,
      placeholder: "BKK-HQ",
      validationHint: "Reference the governed location code when assigned.",
    },
  ],
  filters: [
    {
      key: "job-position-code",
      label: "Code",
      field: "code",
      kind: "text",
      operator: "contains",
      placeholder: "Search code",
    },
    {
      key: "job-position-status",
      label: "Status",
      field: "status",
      kind: "status",
      operator: "equals",
      options: [
        { label: "Active", value: "active" },
        { label: "Planned", value: "planned" },
        { label: "Frozen", value: "frozen" },
        { label: "Closed", value: "closed" },
      ],
    },
  ],
  forms: [
    {
      key: "job-position-create",
      label: "Create job position",
      fieldKeys: [
        "code",
        "title",
        "orgUnitId",
        "status",
        "costCenterCode",
        "locationCode",
      ],
      sectionKeys: ["job-position-identity", "job-position-governance"],
      submitActionKey: "job-position-create",
      cancelActionKey: "cancel",
      layout: "grid",
    },
  ],
  actions: [
    {
      key: "job-position-create",
      label: "Create",
      kind: "create",
      placement: "primary",
    },
  ],
  sections: [
    {
      key: "job-position-identity",
      label: "Identity",
      fieldKeys: ["code", "title", "orgUnitId", "status"],
      columns: 2,
    },
    {
      key: "job-position-governance",
      label: "Governance",
      fieldKeys: ["costCenterCode", "locationCode"],
      columns: 2,
      collapsible: true,
    },
  ],
  states: [
    {
      key: "job-position-draft",
      label: "Draft",
      uiState: "empty",
      tone: "neutral",
    },
    {
      key: "job-position-ready",
      label: "Ready",
      uiState: "ready",
      tone: "success",
    },
    {
      key: "job-position-closed",
      label: "Closed",
      uiState: "forbidden",
      tone: "warning",
    },
  ],
  table: {
    defaultSort: "title",
    title: "Job position directory",
    columns: [
      {
        key: "code",
        label: "Code",
        field: "code",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "title",
        label: "Title",
        field: "title",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "orgUnitId",
        label: "Org unit",
        field: "orgUnitId",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "status",
        label: "Status",
        field: "status",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
    ],
  },
};
