import type { EntityMetadata } from "@repo/metadata";

export const customerMetadata: EntityMetadata = {
  id: "master-data.customers",
  entity: "customer",
  title: "Customers",
  description:
    "Tenant-scoped customer master-data for account management, billing, and service operations.",
  labels: {
    singular: "Customer",
    plural: "Customers",
  },
  presentation: {
    density: "default",
    icon: "users",
    size: "md",
    tone: "info",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: "master-data.customers:read",
    reason: "Read customer records",
    scope: "tenant",
    subject: "customer",
  },
  fields: [
    {
      key: "code",
      label: "Code",
      kind: "text",
      required: true,
      placeholder: "CUST-001",
      validationHint: "Use a stable customer code.",
    },
    {
      key: "name",
      label: "Name",
      kind: "text",
      required: true,
      placeholder: "Acme Corporation",
      validationHint: "Use the registered or display name.",
    },
    {
      key: "email",
      label: "Primary email",
      kind: "text",
      placeholder: "billing@example.com",
      permissionHint: "master-data.customers:contact:view",
    },
    {
      key: "status",
      label: "Status",
      kind: "select",
      required: true,
      validationHint:
        "Use active for open accounts and inactive for closed accounts.",
    },
  ],
  filters: [
    {
      key: "customer-code",
      label: "Code",
      field: "code",
      kind: "text",
      operator: "contains",
      placeholder: "Search code",
    },
    {
      key: "customer-status",
      label: "Status",
      field: "status",
      kind: "status",
      operator: "equals",
      options: [
        {
          label: "Active",
          value: "active",
        },
        {
          label: "Inactive",
          value: "inactive",
        },
      ],
    },
  ],
  forms: [
    {
      key: "customer-create",
      label: "Create customer",
      fieldKeys: ["code", "name", "email", "status"],
      sectionKeys: [
        "customer-identity",
        "customer-contact",
        "customer-lifecycle",
      ],
      submitActionKey: "customer-create",
      cancelActionKey: "cancel",
      layout: "grid",
    },
    {
      key: "customer-edit",
      label: "Edit customer",
      fieldKeys: ["code", "name", "email", "status"],
      sectionKeys: [
        "customer-identity",
        "customer-contact",
        "customer-lifecycle",
      ],
      submitActionKey: "customer-save",
      cancelActionKey: "cancel",
      layout: "grid",
    },
  ],
  actions: [
    {
      key: "customer-create",
      label: "Create",
      kind: "create",
      placement: "primary",
      permissionHint: "master-data.customers:write",
    },
    {
      key: "customer-save",
      label: "Save changes",
      kind: "update",
      placement: "primary",
      permissionHint: "master-data.customers:write",
    },
    {
      key: "customer-archive",
      label: "Archive",
      kind: "archive",
      placement: "overflow",
      dangerous: true,
      confirmMessage: "Archive this customer record?",
      permissionHint: "master-data.customers:write",
      stateTransition: {
        from: ["active"],
        to: "inactive",
      },
    },
    {
      key: "customer-restore",
      label: "Restore",
      kind: "restore",
      placement: "overflow",
      permissionHint: "master-data.customers:write",
      stateTransition: {
        from: ["inactive"],
        to: "active",
      },
    },
  ],
  sections: [
    {
      key: "customer-identity",
      label: "Identity",
      fieldKeys: ["code", "name"],
      columns: 2,
    },
    {
      key: "customer-contact",
      label: "Contact",
      fieldKeys: ["email"],
      columns: 1,
      collapsible: true,
    },
    {
      key: "customer-lifecycle",
      label: "Lifecycle",
      fieldKeys: ["status"],
      columns: 2,
    },
  ],
  states: [
    {
      key: "customer-draft",
      label: "Draft",
      uiState: "empty",
      tone: "neutral",
    },
    {
      key: "customer-ready",
      label: "Ready",
      uiState: "ready",
      tone: "success",
    },
    {
      key: "customer-inactive",
      label: "Inactive",
      uiState: "forbidden",
      tone: "warning",
    },
  ],
  table: {
    defaultSort: "name",
    title: "Customer directory",
    columns: [
      {
        key: "code",
        label: "Code",
        field: "code",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "name",
        label: "Name",
        field: "name",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "email",
        label: "Email",
        field: "email",
        kind: "email",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "status",
        label: "Status",
        field: "status",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
    ],
  },
};
