export type {
  DocumentsManagementAcknowledgment,
  DocumentsManagementAcknowledgmentMethod,
  DocumentsManagementAuditAction,
  DocumentsManagementAuditEvent,
  DocumentsManagementDocument,
  DocumentsManagementDocumentCategory,
  DocumentsManagementDocumentQuery,
  DocumentsManagementDocumentReference,
  DocumentsManagementDocumentStatus,
  DocumentsManagementDocumentSummary,
  DocumentsManagementDocumentType,
  DocumentsManagementDocumentVersion,
  DocumentsManagementDocumentVersionState,
  DocumentsManagementDocumentVisibility,
  DocumentsManagementReadContext,
  DocumentsManagementRetention,
  DocumentsManagementRetentionAction,
  DocumentsManagementWriteContext,
} from "../schema.ts";
export type {
  DocumentsManagementDocumentExpiringProjection,
  DocumentsManagementDocumentProjection,
  DocumentsManagementDocumentReadinessProjection,
  DocumentsManagementDocumentSummaryProjection,
  DocumentsManagementRecord,
  DocumentsManagementRecordProjection,
  DocumentsManagementStatus,
} from "./projection.contract.ts";
