import "server-only";

export type {
  HrOrgAccessDecision,
  HrOrgActionResult,
  HrOrgAuditEvent,
  HrOrgAuditQuery,
  HrOrgChartNode,
  HrOrgChartNodeProjection,
  HrOrgListQuery,
  HrOrgMutationResult,
  HrOrgNodeInput,
  HrOrgOverviewProjection,
  HrOrgPageModel,
  HrOrgPageModelInput,
  HrOrgPolicyContext,
  HrOrgPositionQuery,
  HrOrgPositionRecord,
  HrOrgReadContext,
  HrOrgReportingRelationshipQuery,
  HrOrgReportingRelationshipRecord,
  HrOrgReportingRelationshipType,
  HrOrgRepositoryEntityType,
  HrOrgScope,
  HrOrgSearchParams,
  HrOrgStatus,
  HrOrgUnitQuery,
  HrOrgUnitRecord,
  HrOrgUnitStatus,
  HrOrgUnitType,
  HrOrgWriteContext,
  ListHrOrgAuditQuery,
  ListHrOrgPositionsQuery,
  ListHrOrgReportingRelationshipsQuery,
  ListHrOrgUnitsQuery,
  OrganizationalChartHierarchyManifest,
  OrganizationalChartHierarchyMetadata,
  UpsertHrOrgPositionCommandInput,
  UpsertHrOrgPositionInput,
  UpsertHrOrgReportingRelationshipCommandInput,
  UpsertHrOrgReportingRelationshipInput,
  UpsertHrOrgUnitCommandInput,
  UpsertHrOrgUnitInput,
} from "./contract.ts";
export {
  hrOrgAccessDecisionReasonSchema,
  hrOrgAccessDecisionSchema,
  hrOrgAuditEventProjectionSchema,
  hrOrgAuditEventSchema,
  hrOrgChartNodeProjectionSchema,
  hrOrgChartNodeSchema,
  hrOrgOverviewProjectionSchema,
  hrOrgOverviewSchema,
  hrOrgPolicyCapabilitySchema,
  hrOrgPolicyContextSchema,
  hrOrgPolicyDecisionInputSchema,
  hrOrgPositionProjectionSchema,
  hrOrgPositionRecordSchema,
  hrOrgReadAccessContextSchema,
  hrOrgReadContextSchema,
  hrOrgReportingRelationshipProjectionSchema,
  hrOrgReportingRelationshipRecordSchema,
  hrOrgReportingRelationshipTypeSchema,
  hrOrgRepositoryEntityTypeSchema,
  hrOrgScopeSchema,
  hrOrgStatusSchema,
  hrOrgUnitProjectionSchema,
  hrOrgUnitRecordSchema,
  hrOrgUnitSchema,
  hrOrgUnitTypeSchema,
  hrOrgWriteAccessContextSchema,
  hrOrgWriteContextSchema,
  hrWorkforceOrgReadPermission,
  hrWorkforceOrgWritePermission,
  listHrOrgAuditQuerySchema,
  listHrOrgPositionsQuerySchema,
  listHrOrgReportingRelationshipsQuerySchema,
  listHrOrgUnitsQuerySchema,
  ORGANIZATIONAL_CHART_HIERARCHY_CONTRACT_VERSION,
  organizationalChartHierarchyManifestSchema,
  organizationalChartHierarchyMetadataSchema,
  organizationalChartHierarchyReadPermission,
  organizationalChartHierarchyRouteContracts,
  organizationalChartHierarchyRoutePaths,
  organizationalChartHierarchyWritePermission,
  upsertHrOrgPositionInputSchema,
  upsertHrOrgReportingRelationshipInputSchema,
  upsertHrOrgUnitInputSchema,
} from "./contract.ts";
export { hrOrgExecutionSurface } from "./execution/index.ts";
export type {
  HrOrgAccessContext,
  HrSuiteFeatureContext,
  HrSuiteFeatureScope,
  OrganizationalChartHierarchyFeatureScope,
} from "./feature-scope.ts";
export {
  hrSuiteFeatureScope as canonicalHrSuiteFeatureScope,
  organizationalChartHierarchyFeatureScope,
} from "./feature-scope.ts";
export {
  type HrOrgRoutePath,
  hrEmployeeDetailRoutePath,
  hrOrgRoutePaths,
} from "./hr.workforce.org-route.contract.ts";
export {
  hrSuiteFeatureSource,
  hrSuiteFeatureSuite,
  organizationalChartHierarchyDomain,
  organizationalChartHierarchyFeature,
  organizationalChartHierarchyFeatureId,
  organizationalChartHierarchyPackageName,
} from "./identity.ts";
export { hrOrgFeatureManifest } from "./manifest.ts";
export { hrOrgFeatureMetadata, hrOrgUiCopy } from "./metadata.ts";
export {
  canReadHrOrg,
  canWriteHrOrg,
  requireHrOrgWriteAccess,
} from "./policy.ts";
export {
  type OrganizationalChartHierarchyCapability,
  organizationalChartHierarchyAuditEventCatalog,
  organizationalChartHierarchyAuditEvents,
  organizationalChartHierarchyCapabilities,
  organizationalChartHierarchyCapabilityCatalog,
  organizationalChartHierarchyExclusions,
  organizationalChartHierarchyOwnedEntities,
} from "./registry/index.ts";
export {
  createHrOrgRecordId,
  emptyHrOrgRepositoryState,
  loadHrOrgRepository,
  mutateHrOrgRepository,
  resetHrOrgRepositoryForTesting,
  saveHrOrgRepository,
} from "./repository.ts";
export { hrOrgFeatureScope } from "./shared/index.ts";
