import type { EntityMetadata } from "@repo/metadata";

const documentCategoryOptions = [
  "employment",
  "identity",
  "qualification",
  "payroll",
  "policy",
  "hr_letter",
  "medical_leave",
  "compliance",
  "training",
  "other",
] as const;

const documentTypeOptions = [
  "offer_letter",
  "appointment_letter",
  "employment_contract",
  "contract_renewal_letter",
  "nric",
  "passport",
  "work_permit",
  "visa",
  "national_id",
  "degree_certificate",
  "professional_certificate",
  "license",
  "training_certificate",
  "bank_form",
  "tax_form",
  "statutory_registration_form",
  "payroll_declaration_reference",
  "employee_handbook_acknowledgment",
  "code_of_conduct_acknowledgment",
  "it_policy_acknowledgment",
  "safety_policy_acknowledgment",
  "confirmation_letter",
  "promotion_letter",
  "transfer_letter",
  "warning_letter",
  "disciplinary_letter",
  "medical_certificate",
  "fitness_certificate",
  "hospitalization_document",
  "maternity_document",
  "consent_form",
  "statutory_declaration",
  "right_to_work_document",
  "regulatory_form",
  "other",
] as const;

const visibilityOptions = ["internal", "restricted", "confidential"] as const;

const documentStatusOptions = [
  "draft",
  "pending_verification",
  "verified",
  "rejected",
  "expired",
  "archived",
] as const;

const toSelectOptions = (values: readonly string[]) =>
  values.map((value) => ({
    label: value
      .replaceAll("_", " ")
      .replace(/\b\w/g, (character) => character.toUpperCase()),
    value,
  }));

export const hrDocumentEntityMetadata: EntityMetadata = {
  id: "hr-suite.employee-management.documents-management",
  entity: "hr.document",
  title: "Documents",
  description:
    "Tenant-scoped HR document records with lifecycle metadata and secured storage references.",
  labels: {
    singular: "Document",
    plural: "Documents",
  },
  presentation: {
    density: "default",
    icon: "file",
    size: "md",
    tone: "info",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: "hr.documents.read",
    reason: "Read HR documents for this tenant",
    scope: "tenant",
    subject: "hr.document",
  },
  fields: [
    { key: "title", label: "Title", kind: "text", required: true },
    { key: "employeeId", label: "Employee", kind: "text", required: true },
    {
      key: "documentCategory",
      label: "Category",
      kind: "select",
      required: true,
    },
    { key: "documentType", label: "Type", kind: "select", required: true },
    {
      key: "status",
      label: "Status",
      kind: "select",
      required: true,
    },
    {
      key: "visibility",
      label: "Visibility",
      kind: "select",
      required: true,
    },
    { key: "mandatory", label: "Mandatory", kind: "switch" },
    { key: "updatedAt", label: "Updated", kind: "date" },
    { key: "expiresAt", label: "Expires", kind: "date" },
    { key: "renewalDueAt", label: "Renewal due", kind: "date" },
    {
      key: "currentVersionNumber",
      label: "Version",
      kind: "text",
    },
    { key: "legalEntityCode", label: "Legal entity", kind: "text" },
    { key: "fileName", label: "File name", kind: "text" },
    { key: "contentType", label: "Content type", kind: "text" },
    { key: "storagePath", label: "Storage path", kind: "text" },
    { key: "description", label: "Description", kind: "textarea" },
    { key: "sourceNotes", label: "Source notes", kind: "textarea" },
    {
      key: "retentionAction",
      label: "Retention action",
      kind: "text",
    },
    { key: "createdAt", label: "Created", kind: "date" },
    { key: "issuedAt", label: "Issued", kind: "date" },
    { key: "verifiedAt", label: "Verified", kind: "date" },
    { key: "rejectedAt", label: "Rejected", kind: "date" },
    { key: "archivedAt", label: "Archived", kind: "date" },
    {
      key: "retentionPeriodDays",
      label: "Retention period",
      kind: "text",
    },
    {
      key: "archiveAfterEmployeeSeparation",
      label: "Archive after separation",
      kind: "switch",
    },
    {
      key: "anonymizeBeforeDeletion",
      label: "Anonymize before deletion",
      kind: "switch",
    },
  ],
  forms: [
    {
      key: "document-upload",
      label: "Upload document",
      fieldKeys: [
        "employeeId",
        "title",
        "documentCategory",
        "documentType",
        "visibility",
        "legalEntityCode",
        "issuedAt",
        "expiresAt",
        "renewalDueAt",
        "description",
        "mandatory",
      ],
      submitActionKey: "document-upload",
      layout: "grid",
    },
  ],
  actions: [
    {
      key: "document-upload",
      label: "Upload document",
      kind: "create",
      placement: "primary",
    },
  ],
  sections: [
    {
      key: "document-details",
      label: "Document facts",
      fieldKeys: [
        "employeeId",
        "legalEntityCode",
        "fileName",
        "contentType",
        "storagePath",
        "description",
        "sourceNotes",
        "retentionAction",
      ],
      columns: 2,
    },
    {
      key: "document-timeline",
      label: "Lifecycle and retention dates",
      fieldKeys: [
        "createdAt",
        "updatedAt",
        "issuedAt",
        "expiresAt",
        "renewalDueAt",
        "verifiedAt",
        "rejectedAt",
        "archivedAt",
        "retentionPeriodDays",
        "archiveAfterEmployeeSeparation",
        "anonymizeBeforeDeletion",
        "mandatory",
      ],
      columns: 2,
    },
  ],
  table: {
    defaultSort: "updatedAt",
    title: "Document directory",
    columns: [
      {
        key: "title",
        label: "Title",
        field: "title",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "status",
        label: "Status",
        field: "status",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
      {
        key: "visibility",
        label: "Visibility",
        field: "visibility",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
      {
        key: "mandatory",
        label: "Mandatory",
        field: "mandatory",
        kind: "text",
        sortable: true,
        align: "center",
        width: "sm",
      },
      {
        key: "employeeId",
        label: "Employee",
        field: "employeeId",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "documentCategory",
        label: "Category",
        field: "documentCategory",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "documentType",
        label: "Type",
        field: "documentType",
        kind: "text",
        sortable: true,
        filterable: true,
        width: "md",
      },
      {
        key: "updatedAt",
        label: "Updated",
        field: "updatedAt",
        kind: "date",
        sortable: true,
        width: "md",
      },
      {
        key: "expiresAt",
        label: "Expires",
        field: "expiresAt",
        kind: "date",
        sortable: true,
        width: "sm",
      },
      {
        key: "renewalDueAt",
        label: "Renewal due",
        field: "renewalDueAt",
        kind: "date",
        sortable: true,
        width: "sm",
      },
      {
        key: "currentVersionNumber",
        label: "Version",
        field: "currentVersionNumber",
        kind: "text",
        sortable: true,
        align: "center",
        width: "sm",
      },
    ],
  },
};

export const hrDocumentUploadFieldOptions = {
  documentCategory: toSelectOptions(documentCategoryOptions),
  documentStatus: toSelectOptions(documentStatusOptions),
  documentType: toSelectOptions(documentTypeOptions),
  visibility: toSelectOptions(visibilityOptions),
} as const;

export const hrDocumentDetailSectionKeys = {
  details: "document-details",
  timeline: "document-timeline",
} as const;
