import type { CssDeclaration } from "../tokens/css-theme";
import { GLOBALS_CSS_UI_SOURCE_GLOBS } from "./globals-css.pipeline";
import {
  GLOBALS_CSS_BASE_LAYER,
  GLOBALS_CSS_COMFORTABLE_DENSITY_DECLARATIONS,
  GLOBALS_CSS_COMPACT_DENSITY_DECLARATIONS,
  GLOBALS_CSS_DARK_DECLARATIONS,
  GLOBALS_CSS_KEYFRAMES,
  GLOBALS_CSS_REDUCED_MOTION_LAYER,
  GLOBALS_CSS_ROOT_DECLARATIONS,
  GLOBALS_CSS_THEME_DECLARATIONS,
  GLOBALS_CSS_UTILITY_DECLARATIONS,
  validateGlobalsCssTokens,
} from "../tokens/css-theme";
import { AFENDA_GLOBALS_CSS_BASE_THEME_PRESET } from "../../contracts/afenda/globals-css.contract";

const GENERATED_BANNER = `/**
 * Generated by @repo/design-system — do not edit manually.
 * Base preset: ${AFENDA_GLOBALS_CSS_BASE_THEME_PRESET}
 * Run: pnpm --filter @repo/design-system globals:css
 */
`;

function renderDeclarations(declarations: readonly CssDeclaration[]): string {
  return declarations.map(([name, value]) => `  ${name}: ${value};`).join("\n");
}

function renderBlock(
  selector: string,
  declarations: readonly CssDeclaration[]
): string {
  return `${selector} {\n${renderDeclarations(declarations)}\n}`;
}

function renderUtility(name: string, body: string): string {
  return `@utility ${name} {\n${body}\n}`;
}

function renderKeyframes(name: keyof typeof GLOBALS_CSS_KEYFRAMES): string {
  const lines = GLOBALS_CSS_KEYFRAMES[name];
  return `@keyframes ${name} {\n${lines
    .map((line) => (line ? `    ${line}` : ""))
    .join("\n")}\n  }`;
}

export function renderGlobalsCss(): string {
  validateGlobalsCssTokens();

  return [
    GENERATED_BANNER.trimEnd(),
    '@import "tailwindcss";',
    '@import "tw-animate-css";',
    '@import "shadcn/tailwind.css";',
    "",
    ...GLOBALS_CSS_UI_SOURCE_GLOBS.map((source) => `@source "${source}";`),
    "",
    "@custom-variant dark (&:where(.dark, .dark *));",
    "",
    renderBlock(":root", GLOBALS_CSS_ROOT_DECLARATIONS),
    "",
    renderBlock(".dark", GLOBALS_CSS_DARK_DECLARATIONS),
    "",
    renderBlock(
      '[data-density="compact"]',
      GLOBALS_CSS_COMPACT_DENSITY_DECLARATIONS
    ),
    "",
    renderBlock(
      '[data-density="comfortable"]',
      GLOBALS_CSS_COMFORTABLE_DENSITY_DECLARATIONS
    ),
    "",
    `@theme inline {\n${renderDeclarations(GLOBALS_CSS_THEME_DECLARATIONS)}\n\n  ${renderKeyframes(
      "shimmer"
    )}\n}`,
    "",
    GLOBALS_CSS_BASE_LAYER,
    "",
    ...GLOBALS_CSS_UTILITY_DECLARATIONS.flatMap(([name, body]) => [
      renderUtility(name, `  ${body}`),
      "",
    ]),
    "",
    GLOBALS_CSS_REDUCED_MOTION_LAYER,
  ].join("\n");
}
