#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const configPath = path.join(root, ".env.config");
const secretPath = path.join(root, ".env.secret");
const dryRun = process.argv.includes("--dry-run");
const command =
  process.argv.find(
    (arg) =>
      !arg.startsWith("--") &&
      arg !== process.argv[0] &&
      arg !== process.argv[1]
  ) ?? "sync";

const generatedHeader = [
  "# Generated by scripts/sync-env.mjs.",
  "# Do not edit this file directly. Edit .env.config and .env.secret instead.",
  "",
].join("\n");

const sourceHeader = [
  "# Human-maintained local environment source.",
  "# Run `pnpm env:sync` to generate workspace .env destinations.",
  "",
].join("\n");

const secretNamePattern =
  /(^|_)(SECRET|TOKEN|PASSWORD|PRIVATE|SERVICE_ROLE|AUTH_TOKEN|WEBHOOK_SECRET|API_KEY|ACCESS_KEY|SECRET_ACCESS_KEY|DSN|DATABASE_URL)($|_)/i;

const publicNamePattern = /^(NEXT_PUBLIC_|PUBLIC_)/;

const ignoredNames = new Set(["NODE_ENV"]);

function fail(message) {
  console.error(message);
  process.exit(1);
}

function readText(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
}

function parseEnv(text) {
  const entries = new Map();
  const order = [];

  for (const line of text.split(/\r?\n/)) {
    const match = line.match(
      /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/
    );
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    if (ignoredNames.has(key)) {
      continue;
    }

    entries.set(key, rawValue.trim());
    order.push(key);
  }

  return { entries, order };
}

function parseEnvFile(filePath) {
  return parseEnv(readText(filePath));
}

function quoteValue(value) {
  const trimmed = value.trim();
  if (
    trimmed === "" ||
    trimmed.startsWith('"') ||
    trimmed.startsWith("'") ||
    /^[A-Za-z0-9_./:@%+=,-]+$/.test(trimmed)
  ) {
    return trimmed;
  }

  return `"${trimmed.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function isSecretKey(key) {
  if (publicNamePattern.test(key)) {
    return false;
  }

  return secretNamePattern.test(key);
}

function collectEnvExamplePaths(dir, matches = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (
      entry.name === "node_modules" ||
      entry.name === ".git" ||
      entry.name === ".next"
    ) {
      continue;
    }

    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectEnvExamplePaths(fullPath, matches);
      continue;
    }

    if (entry.name === ".env.example") {
      matches.push(fullPath);
    }
  }

  return matches;
}

function collectExistingEnvPaths() {
  const explicitPaths = [
    ".env",
    ".env.local",
    "apps/app/.env",
    "apps/app/.env.local",
    "apps/api/.env",
    "apps/api/.env.local",
    "apps/web/.env",
    "apps/web/.env.local",
    "packages/database/.env",
    "packages/storage/.env",
    "packages/search/.env",
    "packages/webhooks/.env",
  ];

  return explicitPaths
    .map((relativePath) => path.join(root, relativePath))
    .filter((filePath) => fs.existsSync(filePath));
}

function writeEnvFile(filePath, entries, keys) {
  const lines = [generatedHeader.trimEnd(), ""];

  for (const key of keys) {
    if (!entries.has(key)) {
      continue;
    }

    lines.push(`${key}=${quoteValue(entries.get(key) ?? "")}`);
  }

  const content = `${lines.join("\n")}\n`;
  const relativePath = path.relative(root, filePath) || ".env";
  if (dryRun) {
    console.log(`would write ${relativePath} (${keys.length} keys)`);
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`wrote ${relativePath} (${keys.length} keys)`);
}

function writeSourceFile(filePath, entries, existingOrder) {
  const allKeys = Array.from(
    new Set([...existingOrder, ...entries.keys()])
  ).sort();
  const lines = [sourceHeader.trimEnd(), ""];

  for (const key of allKeys) {
    if (!entries.has(key)) {
      continue;
    }

    lines.push(`${key}=${quoteValue(entries.get(key) ?? "")}`);
  }

  const relativePath = path.relative(root, filePath);
  if (dryRun) {
    console.log(`would update ${relativePath} (${allKeys.length} keys)`);
    return;
  }

  fs.writeFileSync(filePath, `${lines.join("\n")}\n`);
  console.log(`updated ${relativePath} (${allKeys.length} keys)`);
}

function loadSources() {
  const config = parseEnvFile(configPath);
  const secret = parseEnvFile(secretPath);
  const merged = new Map([...config.entries, ...secret.entries]);

  return { config, secret, merged };
}

function getTargetPath(envExamplePath) {
  const relativeDir = path.relative(root, path.dirname(envExamplePath));
  const [workspaceType] = relativeDir.split(path.sep);
  const targetName = workspaceType === "apps" ? ".env.local" : ".env";
  return path.join(path.dirname(envExamplePath), targetName);
}

function sync() {
  const { merged } = loadSources();
  const allKeys = Array.from(merged.keys()).sort();

  if (allKeys.length === 0) {
    fail("No keys found in .env.config or .env.secret.");
  }

  writeEnvFile(path.join(root, ".env"), merged, allKeys);
  writeEnvFile(path.join(root, ".env.local"), merged, allKeys);

  for (const examplePath of collectEnvExamplePaths(root)) {
    if (examplePath === path.join(root, ".env.example")) {
      continue;
    }

    const example = parseEnvFile(examplePath);
    const targetEntries = new Map();
    for (const key of example.order) {
      targetEntries.set(key, merged.get(key) ?? example.entries.get(key) ?? "");
    }

    writeEnvFile(getTargetPath(examplePath), targetEntries, example.order);
  }
}

function consolidate() {
  const { config, secret } = loadSources();
  let addedConfig = 0;
  let addedSecret = 0;

  for (const envPath of collectExistingEnvPaths()) {
    const parsed = parseEnvFile(envPath);
    for (const [key, value] of parsed.entries) {
      if (config.entries.has(key) || secret.entries.has(key)) {
        continue;
      }

      if (isSecretKey(key)) {
        secret.entries.set(key, value);
        addedSecret += 1;
      } else {
        config.entries.set(key, value);
        addedConfig += 1;
      }
    }
  }

  writeSourceFile(configPath, config.entries, config.order);
  writeSourceFile(secretPath, secret.entries, secret.order);
  console.log(
    `consolidated ${addedConfig} config keys and ${addedSecret} secret keys`
  );
}

if (command === "sync") {
  sync();
} else if (command === "consolidate") {
  consolidate();
} else if (command === "doctor") {
  const { config, secret, merged } = loadSources();
  console.log(`config keys: ${config.entries.size}`);
  console.log(`secret keys: ${secret.entries.size}`);
  console.log(`merged keys: ${merged.size}`);
  console.log(`env examples: ${collectEnvExamplePaths(root).length}`);
} else {
  fail("Usage: pnpm env:sync | pnpm env:consolidate | pnpm env:doctor");
}
