import type { EntityMetadata } from "@repo/metadata";

export const orgUnitMetadata: EntityMetadata = {
  id: "master-data.org-units",
  entity: "org-unit",
  title: "Org Units",
  description:
    "Governed metadata for organizational units shared across workforce structure, reporting, and payroll alignment.",
  labels: {
    singular: "Org unit",
    plural: "Org units",
  },
  presentation: {
    density: "default",
    icon: "network",
    size: "md",
    tone: "info",
    variant: "outline",
  },
  permissionHint: {
    action: "view",
    claim: "master-data.org-units:read",
    reason: "Read organizational unit records",
    scope: "tenant",
    subject: "org-unit",
  },
  fields: [
    {
      key: "code",
      label: "Code",
      kind: "text",
      required: true,
      placeholder: "ORG-001",
      validationHint: "Use a stable organizational unit code.",
    },
    {
      key: "name",
      label: "Name",
      kind: "text",
      required: true,
      placeholder: "Regional Operations",
      validationHint: "Use the organization-facing unit name.",
    },
    {
      key: "unitType",
      label: "Unit type",
      kind: "select",
      required: true,
      validationHint:
        "Choose the canonical structure type used by workforce and payroll modules.",
    },
    {
      key: "status",
      label: "Status",
      kind: "select",
      required: true,
      validationHint:
        "Use planned before activation, frozen for temporary stops, and closed for retired units.",
    },
    {
      key: "parentOrgUnitId",
      label: "Parent org unit",
      kind: "text",
      required: false,
      placeholder: "Parent unit ID",
      validationHint:
        "Reference the immediate parent in the organizational tree.",
    },
    {
      key: "costCenterCode",
      label: "Cost center",
      kind: "text",
      required: false,
      placeholder: "CC-100",
      validationHint: "Use the governed cost center code when assigned.",
    },
    {
      key: "locationCode",
      label: "Location",
      kind: "text",
      required: false,
      placeholder: "BKK-HQ",
      validationHint: "Reference the governed location code when assigned.",
    },
    {
      key: "legalEntityCode",
      label: "Legal entity",
      kind: "text",
      required: false,
      placeholder: "LE-SEA",
      validationHint: "Reference the governed legal entity code when assigned.",
    },
  ],
  filters: [
    {
      key: "org-unit-code",
      label: "Code",
      field: "code",
      kind: "text",
      operator: "contains",
      placeholder: "Search code",
    },
    {
      key: "org-unit-type",
      label: "Type",
      field: "unitType",
      kind: "select",
      operator: "equals",
    },
    {
      key: "org-unit-status",
      label: "Status",
      field: "status",
      kind: "status",
      operator: "equals",
      options: [
        { label: "Active", value: "active" },
        { label: "Planned", value: "planned" },
        { label: "Frozen", value: "frozen" },
        { label: "Closed", value: "closed" },
      ],
    },
  ],
  forms: [
    {
      key: "org-unit-create",
      label: "Create org unit",
      fieldKeys: [
        "code",
        "name",
        "unitType",
        "status",
        "parentOrgUnitId",
        "costCenterCode",
        "locationCode",
        "legalEntityCode",
      ],
      sectionKeys: ["org-unit-identity", "org-unit-governance"],
      submitActionKey: "org-unit-create",
      cancelActionKey: "cancel",
      layout: "grid",
    },
  ],
  actions: [
    {
      key: "org-unit-create",
      label: "Create",
      kind: "create",
      placement: "primary",
    },
  ],
  sections: [
    {
      key: "org-unit-identity",
      label: "Identity",
      fieldKeys: ["code", "name", "unitType", "status"],
      columns: 2,
    },
    {
      key: "org-unit-governance",
      label: "Governance",
      fieldKeys: [
        "parentOrgUnitId",
        "costCenterCode",
        "locationCode",
        "legalEntityCode",
      ],
      columns: 2,
      collapsible: true,
    },
  ],
  states: [
    {
      key: "org-unit-draft",
      label: "Draft",
      uiState: "empty",
      tone: "neutral",
    },
    {
      key: "org-unit-ready",
      label: "Ready",
      uiState: "ready",
      tone: "success",
    },
    {
      key: "org-unit-closed",
      label: "Closed",
      uiState: "forbidden",
      tone: "warning",
    },
  ],
  table: {
    defaultSort: "name",
    title: "Org unit directory",
    columns: [
      {
        key: "code",
        label: "Code",
        field: "code",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "name",
        label: "Name",
        field: "name",
        sortable: true,
        filterable: true,
        width: "lg",
      },
      {
        key: "unitType",
        label: "Type",
        field: "unitType",
        sortable: true,
        filterable: true,
        width: "sm",
      },
      {
        key: "status",
        label: "Status",
        field: "status",
        kind: "status",
        sortable: true,
        filterable: true,
        align: "center",
        width: "sm",
      },
    ],
  },
};
