export type MetadataUiManifestKind = "action" | "field" | "section";

export type MetadataUiManifestEntry = {
  kind: MetadataUiManifestKind;
  registryKey: string;
  rendererExport: string;
  rendererPath: string;
  composeGroup: string;
  title: string;
  description?: string;
  contractKind?: string;
  featureId?: string;
  fixture: boolean;
  moduleId?: string;
  ownerPackage?: string;
  publicExport: boolean;
  smokeTest: boolean;
  version?: string;
};

export type MetadataUiManifest = {
  renderers: readonly MetadataUiManifestEntry[];
};

export const metadataUiManifest = {
  renderers: [
    {
      composeGroup: "button",
      contractKind: "custom",
      fixture: true,
      kind: "action",
      publicExport: true,
      registryKey: "button",
      rendererExport: "ButtonActionRenderer",
      rendererPath: "../renderers/actions/button-action.renderer",
      smokeTest: true,
      title: "Button action renderer",
    },
    {
      composeGroup: "alert-dialog",
      contractKind: "delete",
      fixture: true,
      kind: "action",
      publicExport: true,
      registryKey: "destructive",
      rendererExport: "DestructiveActionRenderer",
      rendererPath: "../renderers/actions/destructive-action.renderer",
      smokeTest: true,
      title: "Destructive action renderer",
    },
    {
      composeGroup: "dropdown-menu",
      contractKind: "custom",
      fixture: true,
      kind: "action",
      publicExport: true,
      registryKey: "menu",
      rendererExport: "MenuActionRenderer",
      rendererPath: "../renderers/actions/menu-action.renderer",
      smokeTest: true,
      title: "Menu action renderer",
    },
    {
      composeGroup: "checkbox",
      contractKind: "checkbox",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "checkbox",
      rendererExport: "CheckboxFieldRenderer",
      rendererPath: "../renderers/fields/checkbox-field.renderer",
      smokeTest: true,
      title: "Checkbox field renderer",
    },
    {
      composeGroup: "date-selector",
      contractKind: "date",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "date",
      rendererExport: "DateFieldRenderer",
      rendererPath: "../renderers/fields/date-field.renderer",
      smokeTest: true,
      title: "Date field renderer",
    },
    {
      composeGroup: "input-group",
      contractKind: "email",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "email",
      rendererExport: "TextFieldRenderer",
      rendererPath: "../renderers/fields/text-field.renderer",
      smokeTest: true,
      title: "Email field renderer",
    },
    {
      composeGroup: "input-group",
      contractKind: "money",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "money",
      rendererExport: "MoneyFieldRenderer",
      rendererPath: "../renderers/fields/money-field.renderer",
      smokeTest: true,
      title: "Money field renderer",
    },
    {
      composeGroup: "number-field",
      contractKind: "number",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "number",
      rendererExport: "NumberFieldRenderer",
      rendererPath: "../renderers/fields/number-field.renderer",
      smokeTest: true,
      title: "Number field renderer",
    },
    {
      composeGroup: "combobox",
      contractKind: "select",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "select",
      rendererExport: "SelectFieldRenderer",
      rendererPath: "../renderers/fields/select-field.renderer",
      smokeTest: true,
      title: "Select field renderer",
    },
    {
      composeGroup: "badge",
      contractKind: "status",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "status",
      rendererExport: "TextFieldRenderer",
      rendererPath: "../renderers/fields/text-field.renderer",
      smokeTest: true,
      title: "Status field renderer",
    },
    {
      composeGroup: "field",
      contractKind: "switch",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "switch",
      rendererExport: "SwitchFieldRenderer",
      rendererPath: "../renderers/fields/switch-field.renderer",
      smokeTest: true,
      title: "Switch field renderer",
    },
    {
      composeGroup: "field",
      contractKind: "textarea",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "textarea",
      rendererExport: "TextareaFieldRenderer",
      rendererPath: "../renderers/fields/textarea-field.renderer",
      smokeTest: true,
      title: "Textarea field renderer",
    },
    {
      composeGroup: "field",
      contractKind: "text",
      fixture: true,
      kind: "field",
      publicExport: true,
      registryKey: "text",
      rendererExport: "TextFieldRenderer",
      rendererPath: "../renderers/fields/text-field.renderer",
      smokeTest: true,
      title: "Text field renderer",
    },
    {
      composeGroup: "timeline",
      contractKind: "activity",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "activity",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Activity section renderer",
    },
    {
      composeGroup: "alert-dialog",
      contractKind: "approval",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "approval",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Approval section renderer",
    },
    {
      composeGroup: "card",
      contractKind: "card",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "card",
      rendererExport: "MetadataCardSectionRenderer",
      rendererPath: "../renderers/sections/metadata-card-section.renderer",
      smokeTest: true,
      title: "Card section renderer",
    },
    {
      composeGroup: "chart",
      contractKind: "chart",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "chart",
      rendererExport: "MetadataCardSectionRenderer",
      rendererPath: "../renderers/sections/metadata-card-section.renderer",
      smokeTest: true,
      title: "Chart section renderer",
    },
    {
      composeGroup: "statistic-card",
      contractKind: "dashboard",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "dashboard",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Dashboard section renderer",
    },
    {
      composeGroup: "card",
      contractKind: "details",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "details",
      rendererExport: "MetadataCardSectionRenderer",
      rendererPath: "../renderers/sections/metadata-card-section.renderer",
      smokeTest: true,
      title: "Details section renderer",
    },
    {
      composeGroup: "file-upload",
      contractKind: "evidence",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "evidence",
      rendererExport: "MetadataCardSectionRenderer",
      rendererPath: "../renderers/sections/metadata-card-section.renderer",
      smokeTest: true,
      title: "Evidence section renderer",
    },
    {
      composeGroup: "field",
      contractKind: "form",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "form",
      rendererExport: "MetadataFormSectionRenderer",
      rendererPath: "../renderers/sections/metadata-form-section.renderer",
      smokeTest: true,
      title: "Form section renderer",
    },
    {
      composeGroup: "kanban",
      contractKind: "kanban",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "kanban",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Kanban section renderer",
    },
    {
      composeGroup: "data-grid",
      contractKind: "list",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "list",
      rendererExport: "MetadataTableSectionRenderer",
      rendererPath: "../renderers/sections/metadata-table-section.renderer",
      smokeTest: true,
      title: "List section renderer",
    },
    {
      composeGroup: "frame",
      contractKind: "section",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "section",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Section renderer",
    },
    {
      composeGroup: "statistic-card",
      contractKind: "stat",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "stat",
      rendererExport: "MetadataCardSectionRenderer",
      rendererPath: "../renderers/sections/metadata-card-section.renderer",
      smokeTest: true,
      title: "Stat section renderer",
    },
    {
      composeGroup: "data-grid",
      contractKind: "table",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "table",
      rendererExport: "MetadataTableSectionRenderer",
      rendererPath: "../renderers/sections/metadata-table-section.renderer",
      smokeTest: true,
      title: "Table section renderer",
    },
    {
      composeGroup: "timeline",
      contractKind: "timeline",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "timeline",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Timeline section renderer",
    },
    {
      composeGroup: "stepper",
      contractKind: "workflow",
      fixture: true,
      kind: "section",
      publicExport: true,
      registryKey: "workflow",
      rendererExport: "MetadataSectionRenderer",
      rendererPath: "../renderers/sections/metadata-section.renderer",
      smokeTest: true,
      title: "Workflow section renderer",
    },
  ],
} as const satisfies MetadataUiManifest;
