process.env.AFENDA_LAM_TRUST_ORCHESTRATION_HEADERS = "true";
process.env.AFENDA_MODULE_CONSOLE_REPOSITORY_MODE = "file";
process.env.AFENDA_HR_CONSOLE_REPOSITORY_MODE = "file";
process.env.AFENDA_EMPLOYEE_RECORDS_REPOSITORY_MODE = "file";
process.env.AFENDA_HR_RECORDS_TRUST_ORCHESTRATION_HEADERS = "true";
