export const permissionCatalog = {
  ai: {
    read: "ai.read",
  },
  audit: {
    read: "audit.read",
  },
  companies: {
    read: "master-data.companies:read",
    write: "master-data.companies:write",
  },
  customers: {
    read: "master-data.customers:read",
    write: "master-data.customers:write",
  },
  hrCompliance: {
    alertsRead: "hr.compliance.alerts.read",
    auditRead: "hr.compliance.audit.read",
    calendarRead: "hr.compliance.calendar.read",
    correctiveActionsRead: "hr.compliance.corrective-actions.read",
    correctiveActionsWrite: "hr.compliance.corrective-actions.write",
    evidenceRead: "hr.compliance.evidence.read",
    evidenceSensitiveRead: "hr.compliance.evidence.sensitive.read",
    evidenceWrite: "hr.compliance.evidence.write",
    exceptionsRead: "hr.compliance.exceptions.read",
    exceptionsWrite: "hr.compliance.exceptions.write",
    filingsRead: "hr.compliance.filings.read",
    filingsWrite: "hr.compliance.filings.write",
    obligationsRead: "hr.compliance.obligations.read",
    obligationsWrite: "hr.compliance.obligations.write",
    overviewRead: "hr.compliance.overview.read",
    reportsExport: "hr.compliance.reports.export",
    reportsRead: "hr.compliance.reports.read",
    requirementsRead: "hr.compliance.requirements.read",
    waiversApprove: "hr.compliance.waivers.approve",
  },
  hrConsole: {
    delegationManage: "hr.console.delegation.manage",
    delegationRead: "hr.console.delegation.read",
    overviewRead: "hr.console.overview.read",
    sectionsRead: "hr.console.sections.read",
  },
  hrLam: {
    attendanceCorrectionsRead: "hr.lam.attendance-corrections.read",
    attendanceCorrectionsWrite: "hr.lam.attendance-corrections.write",
    attendanceRead: "hr.lam.attendance.read",
    attendanceWrite: "hr.lam.attendance.write",
    attendancePolicyRead: "hr.lam.attendance-policy.read",
    attendancePolicyWrite: "hr.lam.attendance-policy.write",
    auditRead: "hr.lam.audit.read",
    calendarsRead: "hr.lam.calendars.read",
    calendarsWrite: "hr.lam.calendars.write",
    encashmentRead: "hr.lam.encashment.read",
    encashmentWrite: "hr.lam.encashment.write",
    leaveApplicationsApprove: "hr.lam.leave-applications.approve",
    leaveApplicationsRead: "hr.lam.leave-applications.read",
    leaveApplicationsWrite: "hr.lam.leave-applications.write",
    leaveBalancesRead: "hr.lam.leave-balances.read",
    leaveBalancesWrite: "hr.lam.leave-balances.write",
    leaveEntitlementsRead: "hr.lam.leave-entitlements.read",
    leaveEntitlementsWrite: "hr.lam.leave-entitlements.write",
    leaveTypesRead: "hr.lam.leave-types.read",
    leaveTypesWrite: "hr.lam.leave-types.write",
    overviewRead: "hr.lam.overview.read",
    payrollReferencesRead: "hr.lam.payroll-references.read",
    reportsExport: "hr.lam.reports.export",
    reportsRead: "hr.lam.reports.read",
  },
  systemAdmin: {
    auditRead: "system-admin.audit.read",
    customizationPublish: "system-admin.customization.publish",
    customizationRead: "system-admin.customization.read",
    healthRead: "system-admin.health.read",
    moduleConsolesAssign: "system-admin.module-consoles.assign",
    moduleConsolesRead: "system-admin.module-consoles.read",
    overviewRead: "system-admin.overview.read",
    tenantSettingsRead: "system-admin.tenant-settings.read",
    tenantSettingsWrite: "system-admin.tenant-settings.write",
    usersAccessRead: "system-admin.users-access.read",
    usersAccessWrite: "system-admin.users-access.write",
  },
  webhooks: {
    manage: "platform.webhooks:manage",
  },
} as const;

export type PermissionCatalog = typeof permissionCatalog;

export type TenantRole = "member" | "manager" | "admin" | "owner";

const tenantRolePermissions: Record<string, string[]> = {
  admin: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrConsole.delegationManage,
    permissionCatalog.hrConsole.delegationRead,
    permissionCatalog.hrConsole.overviewRead,
    permissionCatalog.hrConsole.sectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsWrite,
    permissionCatalog.hrLam.attendanceRead,
    permissionCatalog.hrLam.attendanceWrite,
    permissionCatalog.hrLam.attendancePolicyRead,
    permissionCatalog.hrLam.attendancePolicyWrite,
    permissionCatalog.hrLam.auditRead,
    permissionCatalog.hrLam.calendarsRead,
    permissionCatalog.hrLam.calendarsWrite,
    permissionCatalog.hrLam.encashmentRead,
    permissionCatalog.hrLam.encashmentWrite,
    permissionCatalog.hrLam.leaveApplicationsApprove,
    permissionCatalog.hrLam.leaveApplicationsRead,
    permissionCatalog.hrLam.leaveApplicationsWrite,
    permissionCatalog.hrLam.leaveBalancesRead,
    permissionCatalog.hrLam.leaveBalancesWrite,
    permissionCatalog.hrLam.leaveEntitlementsRead,
    permissionCatalog.hrLam.leaveEntitlementsWrite,
    permissionCatalog.hrLam.leaveTypesRead,
    permissionCatalog.hrLam.leaveTypesWrite,
    permissionCatalog.hrLam.overviewRead,
    permissionCatalog.hrLam.payrollReferencesRead,
    permissionCatalog.hrLam.reportsExport,
    permissionCatalog.hrLam.reportsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.moduleConsolesAssign,
    permissionCatalog.systemAdmin.moduleConsolesRead,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
  manager: [
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrLam.attendanceCorrectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsWrite,
    permissionCatalog.hrLam.attendanceRead,
    permissionCatalog.hrLam.leaveApplicationsApprove,
    permissionCatalog.hrLam.leaveApplicationsRead,
    permissionCatalog.hrLam.leaveApplicationsWrite,
    permissionCatalog.hrLam.leaveBalancesRead,
    permissionCatalog.hrLam.leaveEntitlementsRead,
    permissionCatalog.hrLam.leaveTypesRead,
    permissionCatalog.hrLam.overviewRead,
    permissionCatalog.hrLam.reportsExport,
    permissionCatalog.hrLam.reportsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.usersAccessRead,
  ],
  member: [
    permissionCatalog.companies.read,
    permissionCatalog.customers.read,
    permissionCatalog.hrLam.attendanceRead,
    permissionCatalog.hrLam.attendanceCorrectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsWrite,
    permissionCatalog.hrLam.leaveApplicationsRead,
    permissionCatalog.hrLam.leaveApplicationsWrite,
    permissionCatalog.hrLam.leaveBalancesRead,
    permissionCatalog.hrLam.leaveTypesRead,
    permissionCatalog.hrLam.reportsRead,
  ],
  owner: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrConsole.delegationManage,
    permissionCatalog.hrConsole.delegationRead,
    permissionCatalog.hrConsole.overviewRead,
    permissionCatalog.hrConsole.sectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsRead,
    permissionCatalog.hrLam.attendanceCorrectionsWrite,
    permissionCatalog.hrLam.attendanceRead,
    permissionCatalog.hrLam.attendanceWrite,
    permissionCatalog.hrLam.attendancePolicyRead,
    permissionCatalog.hrLam.attendancePolicyWrite,
    permissionCatalog.hrLam.auditRead,
    permissionCatalog.hrLam.calendarsRead,
    permissionCatalog.hrLam.calendarsWrite,
    permissionCatalog.hrLam.encashmentRead,
    permissionCatalog.hrLam.encashmentWrite,
    permissionCatalog.hrLam.leaveApplicationsApprove,
    permissionCatalog.hrLam.leaveApplicationsRead,
    permissionCatalog.hrLam.leaveApplicationsWrite,
    permissionCatalog.hrLam.leaveBalancesRead,
    permissionCatalog.hrLam.leaveBalancesWrite,
    permissionCatalog.hrLam.leaveEntitlementsRead,
    permissionCatalog.hrLam.leaveEntitlementsWrite,
    permissionCatalog.hrLam.leaveTypesRead,
    permissionCatalog.hrLam.leaveTypesWrite,
    permissionCatalog.hrLam.overviewRead,
    permissionCatalog.hrLam.payrollReferencesRead,
    permissionCatalog.hrLam.reportsExport,
    permissionCatalog.hrLam.reportsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.moduleConsolesAssign,
    permissionCatalog.systemAdmin.moduleConsolesRead,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
};

export const resolvePermissionsForTenantRole = (role: string): string[] =>
  tenantRolePermissions[role] ?? [];
