export const permissionCatalog = {
  ai: {
    read: "ai.read",
  },
  audit: {
    read: "audit.read",
  },
  companies: {
    read: "master-data.companies:read",
    write: "master-data.companies:write",
  },
  customers: {
    read: "master-data.customers:read",
    write: "master-data.customers:write",
  },
  hrCompliance: {
    alertsRead: "hr.compliance.alerts.read",
    auditRead: "hr.compliance.audit.read",
    calendarRead: "hr.compliance.calendar.read",
    correctiveActionsRead: "hr.compliance.corrective-actions.read",
    correctiveActionsWrite: "hr.compliance.corrective-actions.write",
    evidenceRead: "hr.compliance.evidence.read",
    evidenceSensitiveRead: "hr.compliance.evidence.sensitive.read",
    evidenceWrite: "hr.compliance.evidence.write",
    exceptionsRead: "hr.compliance.exceptions.read",
    exceptionsWrite: "hr.compliance.exceptions.write",
    filingsRead: "hr.compliance.filings.read",
    filingsWrite: "hr.compliance.filings.write",
    obligationsRead: "hr.compliance.obligations.read",
    obligationsWrite: "hr.compliance.obligations.write",
    overviewRead: "hr.compliance.overview.read",
    reportsExport: "hr.compliance.reports.export",
    reportsRead: "hr.compliance.reports.read",
    requirementsRead: "hr.compliance.requirements.read",
    waiversApprove: "hr.compliance.waivers.approve",
  },
  hrEmployeeSelfservicePortal: {
    profileRead: "hr.employee-selfservice-portal.profile.read",
    recordsRead: "hr.employee-selfservice-portal.records.read",
    recordsReadAll: "hr.employee-selfservice-portal.records.read-all",
    sensitiveRead: "hr.employee-selfservice-portal.sensitive.read",
    write: "hr.employee-selfservice-portal.write",
  },
  systemAdmin: {
    auditRead: "system-admin.audit.read",
    customizationPublish: "system-admin.customization.publish",
    customizationRead: "system-admin.customization.read",
    healthRead: "system-admin.health.read",
    integrationsRead: "system-admin.integrations.read",
    integrationsWrite: "system-admin.integrations.write",
    overviewRead: "system-admin.overview.read",
    tenantSettingsRead: "system-admin.tenant-settings.read",
    tenantSettingsWrite: "system-admin.tenant-settings.write",
    usersAccessRead: "system-admin.users-access.read",
    usersAccessWrite: "system-admin.users-access.write",
  },
  webhooks: {
    manage: "platform.webhooks:manage",
  },
} as const;

export type PermissionCatalog = typeof permissionCatalog;

export type TenantRole = "member" | "manager" | "admin" | "owner";

const tenantRolePermissions: Record<string, string[]> = {
  admin: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.integrationsWrite,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
  manager: [
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.usersAccessRead,
  ],
  member: [
    permissionCatalog.companies.read,
    permissionCatalog.customers.read,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
  ],
  owner: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.integrationsWrite,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
};

export const resolvePermissionsForTenantRole = (role: string): string[] =>
  tenantRolePermissions[role] ?? [];
