export const permissionCatalog = {
  ai: {
    read: "ai.read",
  },
  audit: {
    read: "audit.read",
  },
  companies: {
    read: "master-data.companies:read",
    write: "master-data.companies:write",
  },
  customers: {
    read: "master-data.customers:read",
    write: "master-data.customers:write",
  },
  hrCompliance: {
    alertsRead: "hr.compliance.alerts.read",
    auditRead: "hr.compliance.audit.read",
    calendarRead: "hr.compliance.calendar.read",
    correctiveActionsRead: "hr.compliance.corrective-actions.read",
    correctiveActionsWrite: "hr.compliance.corrective-actions.write",
    evidenceRead: "hr.compliance.evidence.read",
    evidenceSensitiveRead: "hr.compliance.evidence.sensitive.read",
    evidenceWrite: "hr.compliance.evidence.write",
    exceptionsRead: "hr.compliance.exceptions.read",
    exceptionsWrite: "hr.compliance.exceptions.write",
    filingsRead: "hr.compliance.filings.read",
    filingsWrite: "hr.compliance.filings.write",
    obligationsRead: "hr.compliance.obligations.read",
    obligationsWrite: "hr.compliance.obligations.write",
    overviewRead: "hr.compliance.overview.read",
    reportsExport: "hr.compliance.reports.export",
    reportsRead: "hr.compliance.reports.read",
    requirementsRead: "hr.compliance.requirements.read",
    waiversApprove: "hr.compliance.waivers.approve",
  },
  hrDocuments: {
    acknowledgeSelf: "hr.documents.acknowledge.self",
    auditRead: "hr.documents.audit.read",
    download: "hr.documents.download",
    read: "hr.documents.read",
    retentionExecute: "hr.documents.retention.execute",
    sensitiveRead: "hr.documents.sensitive.read",
    write: "hr.documents.write",
  },
  hrEmployees: {
    read: "hr.employees.read",
    sensitiveRead: "hr.employees.sensitive.read",
    write: "hr.employees.write",
  },
  hrEmployeeSelfservicePortal: {
    profileRead: "hr.employee-selfservice-portal.profile.read",
    recordsRead: "hr.employee-selfservice-portal.records.read",
    recordsReadAll: "hr.employee-selfservice-portal.records.read-all",
    sensitiveRead: "hr.employee-selfservice-portal.sensitive.read",
    write: "hr.employee-selfservice-portal.write",
  },
  hrOffboarding: {
    approvalsRead: "hr.offboarding.approvals.read",
    approvalsWrite: "hr.offboarding.approvals.write",
    auditRead: "hr.offboarding.audit.read",
    casesRead: "hr.offboarding.cases.read",
    casesWrite: "hr.offboarding.cases.write",
    governanceWrite: "hr.offboarding.governance.write",
    overviewRead: "hr.offboarding.overview.read",
    sensitiveRead: "hr.offboarding.sensitive.read",
  },
  hrLifecycle: {
    auditRead: "hr.lifecycle.audit.read",
    historyRead: "hr.lifecycle.history.read",
    overviewRead: "hr.lifecycle.overview.read",
    sensitiveRead: "hr.lifecycle.sensitive.read",
    stagesRead: "hr.lifecycle.stages.read",
    transitionsWrite: "hr.lifecycle.transitions.write",
    workflowRead: "hr.lifecycle.workflow.read",
    workflowWrite: "hr.lifecycle.workflow.write",
  },
  hrOrganizationStructure: {
    auditRead: "hr.organization_structure.audit.read",
    positionsRead: "hr.organization_structure.positions.read",
    reportingLinesRead: "hr.organization_structure.reporting_lines.read",
    structureRead: "hr.organization_structure.read",
    structureWrite: "hr.organization_structure.write",
    unitsRead: "hr.organization_structure.units.read",
  },
  systemAdmin: {
    auditRead: "system-admin.audit.read",
    customizationPublish: "system-admin.customization.publish",
    customizationRead: "system-admin.customization.read",
    healthRead: "system-admin.health.read",
    integrationsRead: "system-admin.integrations.read",
    integrationsWrite: "system-admin.integrations.write",
    overviewRead: "system-admin.overview.read",
    tenantSettingsRead: "system-admin.tenant-settings.read",
    tenantSettingsWrite: "system-admin.tenant-settings.write",
    usersAccessRead: "system-admin.users-access.read",
    usersAccessWrite: "system-admin.users-access.write",
  },
  webhooks: {
    manage: "platform.webhooks:manage",
  },
} as const;

export type PermissionCatalog = typeof permissionCatalog;

export type TenantRole = "member" | "manager" | "admin" | "owner";

const tenantRolePermissions: Record<string, string[]> = {
  admin: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrDocuments.acknowledgeSelf,
    permissionCatalog.hrDocuments.auditRead,
    permissionCatalog.hrDocuments.download,
    permissionCatalog.hrDocuments.read,
    permissionCatalog.hrDocuments.retentionExecute,
    permissionCatalog.hrDocuments.sensitiveRead,
    permissionCatalog.hrDocuments.write,
    permissionCatalog.hrEmployees.read,
    permissionCatalog.hrEmployees.sensitiveRead,
    permissionCatalog.hrEmployees.write,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.hrOffboarding.approvalsRead,
    permissionCatalog.hrOffboarding.approvalsWrite,
    permissionCatalog.hrOffboarding.auditRead,
    permissionCatalog.hrOffboarding.casesRead,
    permissionCatalog.hrOffboarding.casesWrite,
    permissionCatalog.hrOffboarding.governanceWrite,
    permissionCatalog.hrOffboarding.overviewRead,
    permissionCatalog.hrOffboarding.sensitiveRead,
    permissionCatalog.hrLifecycle.auditRead,
    permissionCatalog.hrLifecycle.historyRead,
    permissionCatalog.hrLifecycle.overviewRead,
    permissionCatalog.hrLifecycle.sensitiveRead,
    permissionCatalog.hrLifecycle.stagesRead,
    permissionCatalog.hrLifecycle.transitionsWrite,
    permissionCatalog.hrLifecycle.workflowRead,
    permissionCatalog.hrLifecycle.workflowWrite,
    permissionCatalog.hrOrganizationStructure.auditRead,
    permissionCatalog.hrOrganizationStructure.positionsRead,
    permissionCatalog.hrOrganizationStructure.reportingLinesRead,
    permissionCatalog.hrOrganizationStructure.structureRead,
    permissionCatalog.hrOrganizationStructure.structureWrite,
    permissionCatalog.hrOrganizationStructure.unitsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.integrationsWrite,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
  manager: [
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrDocuments.auditRead,
    permissionCatalog.hrDocuments.download,
    permissionCatalog.hrDocuments.read,
    permissionCatalog.hrDocuments.retentionExecute,
    permissionCatalog.hrDocuments.write,
    permissionCatalog.hrEmployees.read,
    permissionCatalog.hrEmployees.write,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.hrOffboarding.approvalsRead,
    permissionCatalog.hrOffboarding.approvalsWrite,
    permissionCatalog.hrOffboarding.casesRead,
    permissionCatalog.hrOffboarding.casesWrite,
    permissionCatalog.hrOffboarding.governanceWrite,
    permissionCatalog.hrOffboarding.overviewRead,
    permissionCatalog.hrLifecycle.historyRead,
    permissionCatalog.hrLifecycle.overviewRead,
    permissionCatalog.hrLifecycle.stagesRead,
    permissionCatalog.hrLifecycle.transitionsWrite,
    permissionCatalog.hrLifecycle.workflowRead,
    permissionCatalog.hrLifecycle.workflowWrite,
    permissionCatalog.hrOrganizationStructure.positionsRead,
    permissionCatalog.hrOrganizationStructure.reportingLinesRead,
    permissionCatalog.hrOrganizationStructure.structureRead,
    permissionCatalog.hrOrganizationStructure.structureWrite,
    permissionCatalog.hrOrganizationStructure.unitsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.usersAccessRead,
  ],
  member: [
    permissionCatalog.companies.read,
    permissionCatalog.customers.read,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
  ],
  owner: [
    permissionCatalog.ai.read,
    permissionCatalog.audit.read,
    permissionCatalog.companies.read,
    permissionCatalog.companies.write,
    permissionCatalog.customers.read,
    permissionCatalog.customers.write,
    permissionCatalog.hrCompliance.alertsRead,
    permissionCatalog.hrCompliance.auditRead,
    permissionCatalog.hrCompliance.calendarRead,
    permissionCatalog.hrCompliance.correctiveActionsRead,
    permissionCatalog.hrCompliance.correctiveActionsWrite,
    permissionCatalog.hrCompliance.evidenceRead,
    permissionCatalog.hrCompliance.evidenceSensitiveRead,
    permissionCatalog.hrCompliance.evidenceWrite,
    permissionCatalog.hrCompliance.exceptionsRead,
    permissionCatalog.hrCompliance.exceptionsWrite,
    permissionCatalog.hrCompliance.filingsRead,
    permissionCatalog.hrCompliance.filingsWrite,
    permissionCatalog.hrCompliance.obligationsRead,
    permissionCatalog.hrCompliance.obligationsWrite,
    permissionCatalog.hrCompliance.overviewRead,
    permissionCatalog.hrCompliance.reportsExport,
    permissionCatalog.hrCompliance.reportsRead,
    permissionCatalog.hrCompliance.requirementsRead,
    permissionCatalog.hrCompliance.waiversApprove,
    permissionCatalog.hrDocuments.acknowledgeSelf,
    permissionCatalog.hrDocuments.auditRead,
    permissionCatalog.hrDocuments.download,
    permissionCatalog.hrDocuments.read,
    permissionCatalog.hrDocuments.retentionExecute,
    permissionCatalog.hrDocuments.sensitiveRead,
    permissionCatalog.hrDocuments.write,
    permissionCatalog.hrEmployees.read,
    permissionCatalog.hrEmployees.sensitiveRead,
    permissionCatalog.hrEmployees.write,
    permissionCatalog.hrEmployeeSelfservicePortal.profileRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsRead,
    permissionCatalog.hrEmployeeSelfservicePortal.recordsReadAll,
    permissionCatalog.hrEmployeeSelfservicePortal.sensitiveRead,
    permissionCatalog.hrEmployeeSelfservicePortal.write,
    permissionCatalog.hrOffboarding.approvalsRead,
    permissionCatalog.hrOffboarding.approvalsWrite,
    permissionCatalog.hrOffboarding.auditRead,
    permissionCatalog.hrOffboarding.casesRead,
    permissionCatalog.hrOffboarding.casesWrite,
    permissionCatalog.hrOffboarding.governanceWrite,
    permissionCatalog.hrOffboarding.overviewRead,
    permissionCatalog.hrOffboarding.sensitiveRead,
    permissionCatalog.hrLifecycle.auditRead,
    permissionCatalog.hrLifecycle.historyRead,
    permissionCatalog.hrLifecycle.overviewRead,
    permissionCatalog.hrLifecycle.sensitiveRead,
    permissionCatalog.hrLifecycle.stagesRead,
    permissionCatalog.hrLifecycle.transitionsWrite,
    permissionCatalog.hrLifecycle.workflowRead,
    permissionCatalog.hrLifecycle.workflowWrite,
    permissionCatalog.hrOrganizationStructure.auditRead,
    permissionCatalog.hrOrganizationStructure.positionsRead,
    permissionCatalog.hrOrganizationStructure.reportingLinesRead,
    permissionCatalog.hrOrganizationStructure.structureRead,
    permissionCatalog.hrOrganizationStructure.structureWrite,
    permissionCatalog.hrOrganizationStructure.unitsRead,
    permissionCatalog.systemAdmin.auditRead,
    permissionCatalog.systemAdmin.customizationPublish,
    permissionCatalog.systemAdmin.customizationRead,
    permissionCatalog.systemAdmin.healthRead,
    permissionCatalog.systemAdmin.integrationsRead,
    permissionCatalog.systemAdmin.integrationsWrite,
    permissionCatalog.systemAdmin.overviewRead,
    permissionCatalog.systemAdmin.tenantSettingsRead,
    permissionCatalog.systemAdmin.tenantSettingsWrite,
    permissionCatalog.systemAdmin.usersAccessRead,
    permissionCatalog.systemAdmin.usersAccessWrite,
    permissionCatalog.webhooks.manage,
  ],
};

export const resolvePermissionsForTenantRole = (role: string): string[] =>
  tenantRolePermissions[role] ?? [];
