import { organizationalChartHierarchyFeatureId } from "../identity.ts";
import { organizationalChartHierarchyCapabilities } from "./capability.ts";

export const organizationalChartHierarchyNavigation = {
  featureId: organizationalChartHierarchyFeatureId,
  basePath: "/hr/org",
  defaultPage: "overview",
  pages: [
    {
      id: "overview",
      path: "/hr/org/overview",
      title: "Organizational Overview",
      navigationLabel: "Overview",
      capability: organizationalChartHierarchyCapabilities.structureRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "org-chart",
      path: "/hr/org/chart",
      title: "Organization Chart",
      navigationLabel: "Chart",
      capability: organizationalChartHierarchyCapabilities.structureRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "units",
      path: "/hr/org/units",
      title: "Organization Units",
      navigationLabel: "Units",
      capability: organizationalChartHierarchyCapabilities.unitsRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "positions",
      path: "/hr/org/positions",
      title: "Positions",
      navigationLabel: "Positions",
      capability: organizationalChartHierarchyCapabilities.positionsRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "reporting-lines",
      path: "/hr/org/reporting-lines",
      title: "Reporting Lines",
      navigationLabel: "Reporting Lines",
      capability: organizationalChartHierarchyCapabilities.reportingLinesRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "vacancies",
      path: "/hr/org/vacancies",
      title: "Vacancies",
      navigationLabel: "Vacancies",
      capability: organizationalChartHierarchyCapabilities.structureRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "headcount",
      path: "/hr/org/headcount",
      title: "Headcount",
      navigationLabel: "Headcount",
      capability: organizationalChartHierarchyCapabilities.structureRead,
      showInNavigation: true,
      showInSearch: true,
    },
    {
      id: "audit-trail",
      path: "/hr/org/audit-trail",
      title: "Audit Trail",
      navigationLabel: "Audit Trail",
      capability: organizationalChartHierarchyCapabilities.auditRead,
      showInNavigation: true,
      showInSearch: true,
    },
  ],
  navigationGroups: [
    {
      id: "structure",
      label: "Structure",
      pages: ["overview", "org-chart", "units", "positions"],
    },
    {
      id: "workforce",
      label: "Workforce",
      pages: ["reporting-lines", "vacancies", "headcount"],
    },
    {
      id: "governance",
      label: "Governance",
      pages: ["audit-trail"],
    },
  ],
} as const;
